/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.myproject.Interfaces;

import javax.swing.ImageIcon;

/**
 *
 * @author Deema
 */
public class About_Us extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(About_Us.class.getName());

    /**
     * Creates new form About_Us
     */
    public About_Us() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/Logo.png")).getImage());
        this.setSize(1020, 670);
        this.setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        About_Us = new javax.swing.JLabel();
        Eighth_line = new javax.swing.JLabel();
        First_line = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        Second_line = new javax.swing.JLabel();
        Third_line = new javax.swing.JLabel();
        Fourth_line = new javax.swing.JLabel();
        Fifth_line = new javax.swing.JLabel();
        Sixith_line = new javax.swing.JLabel();
        Ninth_line = new javax.swing.JLabel();
        Seventh_line = new javax.swing.JLabel();
        Pink_Bar = new javax.swing.JLabel();
        White_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("About Us");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1440, 1038));
        getContentPane().setLayout(null);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink_logo.png"))); // NOI18N
        getContentPane().add(logo);
        logo.setBounds(0, 0, 140, 100);

        About_Us.setFont(new java.awt.Font("Lucida Fax", 3, 36)); // NOI18N
        About_Us.setForeground(new java.awt.Color(255, 102, 102));
        About_Us.setText("About US");
        getContentPane().add(About_Us);
        About_Us.setBounds(400, 30, 180, 43);

        Eighth_line.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Eighth_line.setForeground(new java.awt.Color(153, 0, 51));
        Eighth_line.setText("🔹 Connect donors and recipients quickly and efficiently without intermediaries.");
        getContentPane().add(Eighth_line);
        Eighth_line.setBounds(60, 440, 900, 25);

        First_line.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        First_line.setForeground(new java.awt.Color(102, 102, 255));
        First_line.setText("Ataya is an online donation system developed in Java to facilitate safe and organized clothing and item");
        getContentPane().add(First_line);
        First_line.setBounds(60, 160, 900, 25);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Exit.png"))); // NOI18N
        Exit.setBorder(null);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(870, 10, 100, 70);

        Second_line.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Second_line.setForeground(new java.awt.Color(102, 102, 255));
        Second_line.setText("donations within the community.");
        getContentPane().add(Second_line);
        Second_line.setBounds(60, 190, 900, 25);

        Third_line.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Third_line.setForeground(new java.awt.Color(102, 102, 255));
        Third_line.setText("The system allows donors to upload clothes or supplies they no longer need, and recipients can easily ");
        getContentPane().add(Third_line);
        Third_line.setBounds(60, 230, 900, 25);

        Fourth_line.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Fourth_line.setForeground(new java.awt.Color(102, 102, 255));
        Fourth_line.setText(" browse and request these donations through a simple and clear interface.");
        getContentPane().add(Fourth_line);
        Fourth_line.setBounds(60, 260, 900, 25);

        Fifth_line.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Fifth_line.setForeground(new java.awt.Color(102, 0, 51));
        Fifth_line.setText("The Ataya project aims to:");
        getContentPane().add(Fifth_line);
        Fifth_line.setBounds(60, 320, 900, 25);

        Sixith_line.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Sixith_line.setForeground(new java.awt.Color(153, 0, 51));
        Sixith_line.setText("🔹 Promote a culture of giving and reuse within the community.");
        getContentPane().add(Sixith_line);
        Sixith_line.setBounds(60, 360, 900, 25);

        Ninth_line.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Ninth_line.setForeground(new java.awt.Color(153, 0, 51));
        Ninth_line.setText("🔹 Ensure a safe donation experience through direct communication and feedback after each transaction.");
        getContentPane().add(Ninth_line);
        Ninth_line.setBounds(60, 480, 900, 25);

        Seventh_line.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Seventh_line.setForeground(new java.awt.Color(153, 0, 51));
        Seventh_line.setText("🔹 Reduce waste and encourage the positive recycling of resources.");
        getContentPane().add(Seventh_line);
        Seventh_line.setBounds(60, 400, 900, 25);

        Pink_Bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink.png"))); // NOI18N
        getContentPane().add(Pink_Bar);
        Pink_Bar.setBounds(0, 0, 1000, 100);

        White_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/White.png"))); // NOI18N
        White_Background.setPreferredSize(new java.awt.Dimension(1440, 1038));
        getContentPane().add(White_Background);
        White_Background.setBounds(0, 0, 1000, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
            // فتح الصفحة الجديدة
        Welcome_Page newPage = new Welcome_Page();
        newPage.setVisible(true);

        // إغلاق الصفحة الحالية
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new About_Us().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel About_Us;
    private javax.swing.JLabel Eighth_line;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Fifth_line;
    private javax.swing.JLabel First_line;
    private javax.swing.JLabel Fourth_line;
    private javax.swing.JLabel Ninth_line;
    private javax.swing.JLabel Pink_Bar;
    private javax.swing.JLabel Second_line;
    private javax.swing.JLabel Seventh_line;
    private javax.swing.JLabel Sixith_line;
    private javax.swing.JLabel Third_line;
    private javax.swing.JLabel White_Background;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
