/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.myproject.Interfaces;

import com.myproject.swproject.DBConnection;
import com.myproject.swproject.UserSession;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Deema
 */
public class Admin_Profile extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Admin_Profile.class.getName());

    /**
     * Creates new form Admin_Profile
     */
    private int userId;
    public Admin_Profile() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/Logo.png")).getImage());
        this.setSize(1020, 670);
        this.setLocationRelativeTo(null); 
        this.userId = UserSession.getUserId(); 
        loadUserData();
    }
    
    private void loadUserData() {
    try (Connection con = DBConnection.getConnection()) {
        String sql = "SELECT * FROM Users WHERE user_id = ?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setInt(1, userId);// Set userId parameter
        ResultSet rs = pst.executeQuery();

        if(rs.next()) {
             // Display user information on the form
            Username_Info.setText(rs.getString("username"));
            Email_Info.setText(rs.getString("email"));
            PhoneNumber_Info.setText(rs.getString("phone"));
            UserType_Info.setText(rs.getString("user_type"));
            Password_info.setText(rs.getString("password"));
        }
    } catch (Exception e) {
              // Show error message if loading fails
        JOptionPane.showMessageDialog(this, "Error loading user data: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Profile = new javax.swing.JLabel();
        User = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Email_Info = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        Password_info = new javax.swing.JLabel();
        Username_Info = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        Phone_Number = new javax.swing.JLabel();
        PhoneNumber_Info = new javax.swing.JLabel();
        User_Type = new javax.swing.JLabel();
        UserType_Info = new javax.swing.JLabel();
        Edit = new javax.swing.JButton();
        Pink_Bar = new javax.swing.JLabel();
        Reports = new javax.swing.JButton();
        Manage_Customers = new javax.swing.JButton();
        Profile_Buttton = new javax.swing.JButton();
        Items = new javax.swing.JButton();
        Menu_Bar = new javax.swing.JLabel();
        White_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Profile");
        getContentPane().setLayout(null);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink_logo.png"))); // NOI18N
        logo.setBorder(null);
        logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoActionPerformed(evt);
            }
        });
        getContentPane().add(logo);
        logo.setBounds(0, 0, 130, 100);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Exit.png"))); // NOI18N
        Exit.setBorder(null);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(870, 10, 100, 70);

        Profile.setFont(new java.awt.Font("Lucida Fax", 3, 36)); // NOI18N
        Profile.setForeground(new java.awt.Color(255, 102, 102));
        Profile.setText("Profile");
        getContentPane().add(Profile);
        Profile.setBounds(420, 30, 130, 43);

        User.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User.png"))); // NOI18N
        getContentPane().add(User);
        User.setBounds(80, 220, 150, 150);

        Email.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Email.setText("Email:");
        getContentPane().add(Email);
        Email.setBounds(290, 140, 100, 43);

        Email_Info.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Email_Info.setForeground(new java.awt.Color(204, 102, 0));
        Email_Info.setText("Email From Database");
        getContentPane().add(Email_Info);
        Email_Info.setBounds(500, 140, 280, 43);

        Username.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Username.setText("Username:");
        getContentPane().add(Username);
        Username.setBounds(290, 190, 130, 43);

        Password_info.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Password_info.setForeground(new java.awt.Color(204, 102, 0));
        Password_info.setText("Password From Database");
        getContentPane().add(Password_info);
        Password_info.setBounds(500, 240, 340, 43);

        Username_Info.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Username_Info.setForeground(new java.awt.Color(204, 102, 0));
        Username_Info.setText("User name From Database");
        getContentPane().add(Username_Info);
        Username_Info.setBounds(500, 190, 340, 43);

        Password.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Password.setText("Password:");
        getContentPane().add(Password);
        Password.setBounds(290, 240, 130, 43);

        Phone_Number.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Phone_Number.setText("Phone Number:");
        getContentPane().add(Phone_Number);
        Phone_Number.setBounds(290, 290, 190, 30);

        PhoneNumber_Info.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        PhoneNumber_Info.setForeground(new java.awt.Color(204, 102, 0));
        PhoneNumber_Info.setText("Phone Number From Database");
        getContentPane().add(PhoneNumber_Info);
        PhoneNumber_Info.setBounds(500, 290, 390, 43);

        User_Type.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        User_Type.setText("User Type:");
        getContentPane().add(User_Type);
        User_Type.setBounds(290, 340, 130, 30);

        UserType_Info.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        UserType_Info.setForeground(new java.awt.Color(204, 102, 0));
        UserType_Info.setText("User Type From Database");
        getContentPane().add(UserType_Info);
        UserType_Info.setBounds(500, 340, 320, 43);

        Edit.setBackground(new java.awt.Color(229, 170, 58));
        Edit.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        Edit.setForeground(new java.awt.Color(102, 51, 0));
        Edit.setText("Edit Profile");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        getContentPane().add(Edit);
        Edit.setBounds(590, 430, 180, 60);

        Pink_Bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink.png"))); // NOI18N
        getContentPane().add(Pink_Bar);
        Pink_Bar.setBounds(0, 0, 1000, 100);

        Reports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Report.png"))); // NOI18N
        Reports.setBorder(null);
        Reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportsActionPerformed(evt);
            }
        });
        getContentPane().add(Reports);
        Reports.setBounds(610, 520, 100, 100);

        Manage_Customers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Manage_Customers.png"))); // NOI18N
        Manage_Customers.setBorder(null);
        Manage_Customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manage_CustomersActionPerformed(evt);
            }
        });
        getContentPane().add(Manage_Customers);
        Manage_Customers.setBounds(310, 520, 120, 100);

        Profile_Buttton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Profile.png"))); // NOI18N
        Profile_Buttton.setBorder(null);
        Profile_Buttton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Profile_ButttonActionPerformed(evt);
            }
        });
        getContentPane().add(Profile_Buttton);
        Profile_Buttton.setBounds(850, 520, 100, 100);

        Items.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Items.png"))); // NOI18N
        Items.setBorder(null);
        Items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemsActionPerformed(evt);
            }
        });
        getContentPane().add(Items);
        Items.setBounds(60, 530, 100, 90);

        Menu_Bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink.png"))); // NOI18N
        getContentPane().add(Menu_Bar);
        Menu_Bar.setBounds(0, 520, 1000, 110);

        White_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/White.png"))); // NOI18N
        White_Background.setToolTipText("");
        getContentPane().add(White_Background);
        White_Background.setBounds(0, 0, 1000, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoActionPerformed

        About_Us about = new About_Us();
        about.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed

        Welcome_Page newPage = new Welcome_Page();
        newPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here
        Edit_Profile newProfile = new Edit_Profile();
        newProfile.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_EditActionPerformed

    private void ReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportsActionPerformed
        Manage_Reports reportsPage = new Manage_Reports();
        reportsPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReportsActionPerformed

    private void Manage_CustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_CustomersActionPerformed
        Manage_Customers customersPage = new  Manage_Customers();
        customersPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Manage_CustomersActionPerformed

    private void Profile_ButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile_ButttonActionPerformed
    // this page
    }//GEN-LAST:event_Profile_ButttonActionPerformed

    private void ItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemsActionPerformed
  
        Manage_Items itemsPage = new Manage_Items();
        itemsPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ItemsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Admin_Profile().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edit;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Email_Info;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Items;
    private javax.swing.JButton Manage_Customers;
    private javax.swing.JLabel Menu_Bar;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Password_info;
    private javax.swing.JLabel PhoneNumber_Info;
    private javax.swing.JLabel Phone_Number;
    private javax.swing.JLabel Pink_Bar;
    private javax.swing.JLabel Profile;
    private javax.swing.JButton Profile_Buttton;
    private javax.swing.JButton Reports;
    private javax.swing.JLabel User;
    private javax.swing.JLabel UserType_Info;
    private javax.swing.JLabel User_Type;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel Username_Info;
    private javax.swing.JLabel White_Background;
    private javax.swing.JButton logo;
    // End of variables declaration//GEN-END:variables
}
