/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.myproject.Interfaces;

import com.myproject.swproject.Item;
import com.myproject.swproject.UserSession;
import java.awt.Image;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Deema
 */
public class Edit_item extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Upload.class.getName());
    private int userId = UserSession.getUserId();
    private File selectedImageFile = null;
    private String currentImageUrl = null; 
    private int itemId;
    /**
     * Creates new form Upload
     */
    public Edit_item() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/Logo.png")).getImage());
        this.setSize(1020, 670);
        this.setLocationRelativeTo(null); 
    }
    
    public Edit_item(int itemId) {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/Logo.png")).getImage());
        this.setSize(1020, 670);
        this.setLocationRelativeTo(null); 
        this.itemId = itemId;
        loadIteminfo();
        
    }
    
private void loadIteminfo() {

    try {
        Item item = Item.getItemById(itemId);

        if (item == null) {
            JOptionPane.showMessageDialog(this, "Error: Item not found.");
            return;
        }

        // Text fields
        Full_Title.setText(item.getTitle());
        Full_Details.setText(item.getDescription());

        // Image
        currentImageUrl = item.getImageUrl();
        photoUrl.setText(currentImageUrl);
        displayDefaultItemImage(currentImageUrl);

        // ComboBoxes
        TypeComboBox.setSelectedItem(item.getItemType().name());
        ConditionComboBox.setSelectedItem(item.getItemCondition().name());

        // Reset selected image (no new image chosen yet)
        selectedImageFile = null;

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(
            this,
            "Error loading item data: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE
        );
    }
}


private void displayDefaultItemImage(String imagePathFromDB) {

    if (imagePathFromDB == null || imagePathFromDB.isEmpty()) {
        Upload_Photo.setIcon(null);
        return;
    }

    ImageIcon icon = new ImageIcon("src/main/resources/" + imagePathFromDB);
    Image img = icon.getImage();

    int labelWidth = Upload_Photo.getWidth();
    int labelHeight = Upload_Photo.getHeight();

    int imgWidth = img.getWidth(null);
    int imgHeight = img.getHeight(null);

    if (imgWidth <= 0 || imgHeight <= 0) {
        Upload_Photo.setIcon(null);
        return;
    }

    double scale = Math.min(
        (double) labelWidth / imgWidth,
        (double) labelHeight / imgHeight
    );

    int newW = (int) (imgWidth * scale);
    int newH = (int) (imgHeight * scale);

    Image scaled = img.getScaledInstance(newW, newH, Image.SCALE_SMOOTH);
    Upload_Photo.setIcon(new ImageIcon(scaled));
}






    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Full_Category1 = new javax.swing.JTextField();
        Upload = new javax.swing.JLabel();
        logo = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        Searsh = new javax.swing.JButton();
        Upload_Button = new javax.swing.JButton();
        Message = new javax.swing.JButton();
        condition = new javax.swing.JLabel();
        Profile_Buttton = new javax.swing.JButton();
        Menu_Bar = new javax.swing.JLabel();
        Pink_Bar = new javax.swing.JLabel();
        Upload_Photo = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Full_Details = new javax.swing.JTextArea();
        photoUrl = new javax.swing.JTextField();
        ConditionComboBox = new javax.swing.JComboBox<>();
        TypeComboBox = new javax.swing.JComboBox<>();
        Details = new javax.swing.JLabel();
        Edit_item = new javax.swing.JButton();
        Full_Title = new javax.swing.JTextField();
        Category1 = new javax.swing.JLabel();
        Category = new javax.swing.JLabel();
        White_Background = new javax.swing.JLabel();

        Full_Category1.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        Full_Category1.setForeground(new java.awt.Color(153, 153, 153));
        Full_Category1.setText("Please enter The Category");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Upload.setFont(new java.awt.Font("Lucida Fax", 3, 36)); // NOI18N
        Upload.setForeground(new java.awt.Color(255, 102, 102));
        Upload.setText("Edit Item");
        getContentPane().add(Upload);
        Upload.setBounds(390, 30, 180, 43);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink_logo.png"))); // NOI18N
        logo.setBorder(null);
        logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoActionPerformed(evt);
            }
        });
        getContentPane().add(logo);
        logo.setBounds(0, 0, 130, 100);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Exit.png"))); // NOI18N
        Exit.setBorder(null);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(870, 10, 100, 70);

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Home.png"))); // NOI18N
        Home.setBorder(null);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        getContentPane().add(Home);
        Home.setBounds(30, 500, 100, 100);

        Searsh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Search.png"))); // NOI18N
        Searsh.setBorder(null);
        Searsh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearshActionPerformed(evt);
            }
        });
        getContentPane().add(Searsh);
        Searsh.setBounds(220, 500, 100, 100);

        Upload_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Upload.png"))); // NOI18N
        Upload_Button.setBorder(null);
        Upload_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Upload_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Upload_Button);
        Upload_Button.setBounds(410, 500, 100, 100);

        Message.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Message.png"))); // NOI18N
        Message.setBorder(null);
        Message.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MessageActionPerformed(evt);
            }
        });
        getContentPane().add(Message);
        Message.setBounds(620, 510, 110, 80);

        condition.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        condition.setText("Condition:");
        getContentPane().add(condition);
        condition.setBounds(50, 360, 130, 43);

        Profile_Buttton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Profile.png"))); // NOI18N
        Profile_Buttton.setBorder(null);
        Profile_Buttton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Profile_ButttonActionPerformed(evt);
            }
        });
        getContentPane().add(Profile_Buttton);
        Profile_Buttton.setBounds(830, 500, 100, 100);

        Menu_Bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink.png"))); // NOI18N
        getContentPane().add(Menu_Bar);
        Menu_Bar.setBounds(0, 500, 1000, 100);

        Pink_Bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink.png"))); // NOI18N
        getContentPane().add(Pink_Bar);
        Pink_Bar.setBounds(0, 0, 1000, 100);

        Upload_Photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Upload_Photo.png"))); // NOI18N
        Upload_Photo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Upload_PhotoActionPerformed(evt);
            }
        });
        getContentPane().add(Upload_Photo);
        Upload_Photo.setBounds(670, 150, 260, 190);

        Title.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Title.setText("Title:");
        getContentPane().add(Title);
        Title.setBounds(50, 130, 100, 40);

        Full_Details.setBackground(new java.awt.Color(255, 255, 255));
        Full_Details.setColumns(20);
        Full_Details.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Full_Details.setLineWrap(true);
        Full_Details.setRows(5);
        Full_Details.setWrapStyleWord(true);
        jScrollPane2.setViewportView(Full_Details);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(190, 190, 360, 106);

        photoUrl.setEditable(false);
        photoUrl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        photoUrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoUrlActionPerformed(evt);
            }
        });
        getContentPane().add(photoUrl);
        photoUrl.setBounds(670, 350, 260, 30);

        ConditionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New", "Like_new", "Good", "Fair" }));
        ConditionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConditionComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(ConditionComboBox);
        ConditionComboBox.setBounds(190, 360, 360, 40);

        TypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clothing", "Bags", "Supplies", "Other" }));
        TypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(TypeComboBox);
        TypeComboBox.setBounds(190, 300, 360, 40);

        Details.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Details.setText("Details:");
        getContentPane().add(Details);
        Details.setBounds(50, 190, 100, 43);

        Edit_item.setBackground(new java.awt.Color(229, 170, 58));
        Edit_item.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        Edit_item.setForeground(new java.awt.Color(102, 51, 0));
        Edit_item.setText("Edit Item");
        Edit_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_itemActionPerformed(evt);
            }
        });
        getContentPane().add(Edit_item);
        Edit_item.setBounds(470, 420, 260, 50);

        Full_Title.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(Full_Title);
        Full_Title.setBounds(190, 130, 360, 40);

        Category1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Category1.setText("Photo:");
        getContentPane().add(Category1);
        Category1.setBounds(760, 100, 90, 50);

        Category.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Category.setText("Category:");
        getContentPane().add(Category);
        Category.setBounds(50, 300, 120, 43);

        White_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/White.png"))); // NOI18N
        White_Background.setToolTipText("");
        getContentPane().add(White_Background);
        White_Background.setBounds(0, 0, 1000, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoActionPerformed
        // TODO add your handling code here:
        About_Us about = new About_Us();
        about.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        Welcome_Page newPage = new Welcome_Page();
        newPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        Home newPage = new Home();
        newPage.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_HomeActionPerformed

    private void SearshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearshActionPerformed

    }//GEN-LAST:event_SearshActionPerformed

    private void Upload_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Upload_ButtonActionPerformed
        // current page
    }//GEN-LAST:event_Upload_ButtonActionPerformed

    private void MessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MessageActionPerformed
        // TODO add your handling code here:
        Notifications newPage = new Notifications();
        newPage.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_MessageActionPerformed

    private void Profile_ButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile_ButttonActionPerformed
        // TODO add your handling code here:
        Profile newPage = new Profile();
        newPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Profile_ButttonActionPerformed

    private void Upload_PhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Upload_PhotoActionPerformed
    JFileChooser fileChooser = new JFileChooser();

    fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter(
            "Image Files", "jpg", "jpeg", "png", "gif"));

    int result = fileChooser.showOpenDialog(this);

    if (result == JFileChooser.APPROVE_OPTION) {

        File selectedFile = fileChooser.getSelectedFile();
        String fileName = selectedFile.getName().toLowerCase();

        if (!(fileName.endsWith(".png") || fileName.endsWith(".jpg") ||
              fileName.endsWith(".jpeg") || fileName.endsWith(".gif"))) {

            JOptionPane.showMessageDialog(this, "Please select a valid image file!");
            return;
        }

        selectedImageFile = selectedFile;

        ImageIcon originalIcon = new ImageIcon(selectedFile.getAbsolutePath());
        Image img = originalIcon.getImage();

        int w = Upload_Photo.getWidth();
        int h = Upload_Photo.getHeight();
        int imgW = img.getWidth(null);
        int imgH = img.getHeight(null);

        double scale = Math.min((double) w / imgW, (double) h / imgH);

        int newW = (int) (imgW * scale);
        int newH = (int) (imgH * scale);

        Image scaled = img.getScaledInstance(newW, newH, Image.SCALE_SMOOTH);
        Upload_Photo.setIcon(new ImageIcon(scaled));
        photoUrl.setText(selectedFile.getName());
    }


        
    }//GEN-LAST:event_Upload_PhotoActionPerformed

    private void ConditionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConditionComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConditionComboBoxActionPerformed

    private void TypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeComboBoxActionPerformed

    private void Edit_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_itemActionPerformed
   try {
        String title = Full_Title.getText().trim();
        String description = Full_Details.getText().trim();
        Item.ItemType type = Item.ItemType.valueOf(TypeComboBox.getSelectedItem().toString().toUpperCase());
        Item.ItemCondition condition = Item.ItemCondition.valueOf(ConditionComboBox.getSelectedItem().toString().toUpperCase());
    


        String imageUrl = currentImageUrl;
   if (selectedImageFile != null) {
    String resourcePath = "src/main/resources/itemsPhotos";
    File destFolder = new File(resourcePath);
    if (!destFolder.exists()) destFolder.mkdirs();

    String newFileName = System.currentTimeMillis() + "_" + selectedImageFile.getName();
    File destFile = new File(destFolder, newFileName);
    Files.copy(selectedImageFile.toPath(), destFile.toPath(), StandardCopyOption.REPLACE_EXISTING);

    imageUrl = "itemsPhotos/" + newFileName;
}

        Item newItem = new Item(userId, title, description, type, condition, imageUrl);
        newItem.setItemId(itemId);
        if (newItem.isValid()) {

            boolean success = Item.updateItem(newItem);

            if (success) {
                JOptionPane.showMessageDialog(this, "Item updated successfully!");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add item. Try again.");
            }
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);

    }
    }//GEN-LAST:event_Edit_itemActionPerformed

    private void photoUrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoUrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_photoUrlActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Upload().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Category;
    private javax.swing.JLabel Category1;
    private javax.swing.JComboBox<String> ConditionComboBox;
    private javax.swing.JLabel Details;
    private javax.swing.JButton Edit_item;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField Full_Category1;
    private javax.swing.JTextArea Full_Details;
    private javax.swing.JTextField Full_Title;
    private javax.swing.JButton Home;
    private javax.swing.JLabel Menu_Bar;
    private javax.swing.JButton Message;
    private javax.swing.JLabel Pink_Bar;
    private javax.swing.JButton Profile_Buttton;
    private javax.swing.JButton Searsh;
    private javax.swing.JLabel Title;
    private javax.swing.JComboBox<String> TypeComboBox;
    private javax.swing.JLabel Upload;
    private javax.swing.JButton Upload_Button;
    private javax.swing.JButton Upload_Photo;
    private javax.swing.JLabel White_Background;
    private javax.swing.JLabel condition;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logo;
    private javax.swing.JTextField photoUrl;
    // End of variables declaration//GEN-END:variables
}
