/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.myproject.Interfaces;

import com.myproject.swproject.DBConnection;
import com.myproject.swproject.UserSession;
import com.myproject.swproject.ValidationUtils;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Deema
 */
public class Edit_Profile extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Edit_Profile.class.getName());
    private int userId;
        private String selectedUserType; // admin or  customer
    /**
     * Creates new form Edit_Profile
     */
    public Edit_Profile() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/Logo.png")).getImage());
        this.setSize(1020, 670);
        this.setLocationRelativeTo(null); 
        this.userId = UserSession.getUserId();
        this.selectedUserType = UserSession.getselectedUserType();
        loadUserData(); // Load user data into the form fields
    }
    
      /**
     * Constructor with userId parameter
     * Initializes the components and loads user data from database
     * @param userId
     */

        
            private void loadUserData() {
        try (Connection con = DBConnection.getConnection()) {
            String sql = "SELECT * FROM Users WHERE user_id = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setInt(1, userId);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                  // Fill the form fields with user data
                Full_Email.setText(rs.getString("email"));
                Full_Username.setText(rs.getString("username"));
                Full_Password.setText(rs.getString("password")); 
                Full_ConfirmPassword.setText(rs.getString("password"));
                Full_Phone.setText(rs.getString("phone"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading user data: " + e.getMessage());
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JButton();
        Edit_Profile = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        Pink_Bar = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Full_Email = new javax.swing.JTextField();
        Update_Email = new javax.swing.JButton();
        Username = new javax.swing.JLabel();
        Full_Username = new javax.swing.JTextField();
        Update_Username = new javax.swing.JButton();
        Password = new javax.swing.JLabel();
        Full_Password = new javax.swing.JTextField();
        Confirm_Password = new javax.swing.JLabel();
        Full_ConfirmPassword = new javax.swing.JPasswordField();
        Update_Password = new javax.swing.JButton();
        Phone_Number = new javax.swing.JLabel();
        Full_Phone = new javax.swing.JTextField();
        Update_PhoneNumber = new javax.swing.JButton();
        Go_Back = new javax.swing.JButton();
        White_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Edit Profile");
        setPreferredSize(new java.awt.Dimension(1440, 1038));
        getContentPane().setLayout(null);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink_logo.png"))); // NOI18N
        logo.setBorder(null);
        logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoActionPerformed(evt);
            }
        });
        getContentPane().add(logo);
        logo.setBounds(0, 0, 130, 100);

        Edit_Profile.setFont(new java.awt.Font("Lucida Fax", 3, 36)); // NOI18N
        Edit_Profile.setForeground(new java.awt.Color(255, 102, 102));
        Edit_Profile.setText("Edit Profile");
        getContentPane().add(Edit_Profile);
        Edit_Profile.setBounds(380, 30, 220, 43);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Exit.png"))); // NOI18N
        Exit.setBorder(null);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(870, 10, 100, 70);

        Pink_Bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink.png"))); // NOI18N
        getContentPane().add(Pink_Bar);
        Pink_Bar.setBounds(0, 0, 1000, 100);

        Email.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Email.setText("Email:");
        getContentPane().add(Email);
        Email.setBounds(110, 160, 100, 43);

        Full_Email.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        Full_Email.setForeground(new java.awt.Color(153, 153, 153));
        Full_Email.setText("Please enter your Email");
        getContentPane().add(Full_Email);
        Full_Email.setBounds(300, 160, 500, 40);

        Update_Email.setBackground(new java.awt.Color(229, 170, 58));
        Update_Email.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        Update_Email.setForeground(new java.awt.Color(102, 51, 0));
        Update_Email.setText("Update");
        Update_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_EmailActionPerformed(evt);
            }
        });
        getContentPane().add(Update_Email);
        Update_Email.setBounds(830, 160, 120, 40);

        Username.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Username.setText("Username:");
        getContentPane().add(Username);
        Username.setBounds(100, 220, 130, 43);

        Full_Username.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        Full_Username.setForeground(new java.awt.Color(153, 153, 153));
        Full_Username.setText("Please enter your Username");
        Full_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Full_UsernameActionPerformed(evt);
            }
        });
        getContentPane().add(Full_Username);
        Full_Username.setBounds(300, 220, 500, 40);

        Update_Username.setBackground(new java.awt.Color(229, 170, 58));
        Update_Username.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        Update_Username.setForeground(new java.awt.Color(102, 51, 0));
        Update_Username.setText("Update");
        Update_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_UsernameActionPerformed(evt);
            }
        });
        getContentPane().add(Update_Username);
        Update_Username.setBounds(830, 220, 120, 40);

        Password.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Password.setText("Password:");
        getContentPane().add(Password);
        Password.setBounds(100, 280, 130, 43);

        Full_Password.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        Full_Password.setForeground(new java.awt.Color(153, 153, 153));
        Full_Password.setText("Please enter your Password");
        Full_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Full_PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Full_Password);
        Full_Password.setBounds(300, 280, 500, 40);

        Confirm_Password.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Confirm_Password.setText("Confirm Password:");
        getContentPane().add(Confirm_Password);
        Confirm_Password.setBounds(100, 360, 230, 30);

        Full_ConfirmPassword.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        Full_ConfirmPassword.setText("Please confirm your Password");
        getContentPane().add(Full_ConfirmPassword);
        Full_ConfirmPassword.setBounds(350, 350, 450, 40);

        Update_Password.setBackground(new java.awt.Color(229, 170, 58));
        Update_Password.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        Update_Password.setForeground(new java.awt.Color(102, 51, 0));
        Update_Password.setText("Update");
        Update_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Update_Password);
        Update_Password.setBounds(830, 350, 120, 40);

        Phone_Number.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Phone_Number.setText("Phone Number:");
        getContentPane().add(Phone_Number);
        Phone_Number.setBounds(100, 410, 190, 30);

        Full_Phone.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        Full_Phone.setForeground(new java.awt.Color(153, 153, 153));
        Full_Phone.setText("Please enter your Phone Number");
        Full_Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Full_PhoneActionPerformed(evt);
            }
        });
        getContentPane().add(Full_Phone);
        Full_Phone.setBounds(350, 410, 450, 40);

        Update_PhoneNumber.setBackground(new java.awt.Color(229, 170, 58));
        Update_PhoneNumber.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        Update_PhoneNumber.setForeground(new java.awt.Color(102, 51, 0));
        Update_PhoneNumber.setText("Update");
        Update_PhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_PhoneNumberActionPerformed(evt);
            }
        });
        getContentPane().add(Update_PhoneNumber);
        Update_PhoneNumber.setBounds(830, 410, 120, 40);

        Go_Back.setBackground(new java.awt.Color(229, 170, 58));
        Go_Back.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        Go_Back.setForeground(new java.awt.Color(102, 51, 0));
        Go_Back.setText("Profile");
        Go_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Go_BackActionPerformed(evt);
            }
        });
        getContentPane().add(Go_Back);
        Go_Back.setBounds(520, 490, 120, 40);

        White_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/White.png"))); // NOI18N
        White_Background.setToolTipText("");
        getContentPane().add(White_Background);
        White_Background.setBounds(0, 0, 1000, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoActionPerformed
        // TODO add your handling code here:
        About_Us about = new About_Us();
        about.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        Welcome_Page newPage = new Welcome_Page();
        newPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void Full_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Full_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Full_UsernameActionPerformed

    private void Full_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Full_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Full_PasswordActionPerformed

    private void Full_PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Full_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Full_PhoneActionPerformed

    private void Update_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_EmailActionPerformed
        String newEmail = Full_Email.getText().trim();
        if (!ValidationUtils.isValidEmail(newEmail)) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email (example@example.com).");
            return;
        }
        try (Connection con = DBConnection.getConnection()) {
            String sql = "UPDATE Users SET email = ? WHERE user_id = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, newEmail);
            pst.setInt(2, userId);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Email updated successfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error updating email: " + e.getMessage());
        }
    }//GEN-LAST:event_Update_EmailActionPerformed

    private void Update_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_UsernameActionPerformed
       String newUsername = Full_Username.getText().trim();
        if (!ValidationUtils.isValidUsername(newUsername)) {
            JOptionPane.showMessageDialog(this, "Username must be at least 4 characters and contain only letters, numbers, or underscores");
            return;
        }
        try (Connection con = DBConnection.getConnection()) {
            String sql = "UPDATE Users SET username = ? WHERE user_id = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, newUsername);
            pst.setInt(2, userId);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Username updated successfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error updating username: " + e.getMessage());
        }
    }//GEN-LAST:event_Update_UsernameActionPerformed

    private void Update_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_PasswordActionPerformed
       String newPassword = Full_Password.getText();
        String confirmPassword = Full_ConfirmPassword.getText();

        if (!newPassword.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match.");
            return;
        }

        if (!ValidationUtils.isValidPassword(newPassword)) {
            JOptionPane.showMessageDialog(this, "Password must be at least 8 characters, with uppercase, lowercase, number, and special character.");
            return;
        }

        try (Connection con = DBConnection.getConnection()) {
            String sql = "UPDATE Users SET password = ? WHERE user_id = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, newPassword);
            pst.setInt(2, userId);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Password updated successfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error updating password: " + e.getMessage());
        }
    }//GEN-LAST:event_Update_PasswordActionPerformed

    private void Update_PhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_PhoneNumberActionPerformed
         String newPhone = Full_Phone.getText().trim();
        if (!ValidationUtils.isValidPhone(newPhone)) {
            JOptionPane.showMessageDialog(this, "Phone number must be 10 digits.");
            return;
        }
        try (Connection con = DBConnection.getConnection()) {
            String sql = "UPDATE Users SET phone = ? WHERE user_id = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, newPhone);
            pst.setInt(2, userId);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Phone number updated successfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error updating phone number: " + e.getMessage());
        }
    }//GEN-LAST:event_Update_PhoneNumberActionPerformed

    private void Go_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Go_BackActionPerformed
        if (selectedUserType == "admin"){
        Admin_Profile newPage = new Admin_Profile();
        newPage.setVisible(true);
        }
        else{
        Profile newPage = new Profile();
        newPage.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_Go_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Edit_Profile().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Confirm_Password;
    private javax.swing.JLabel Edit_Profile;
    private javax.swing.JLabel Email;
    private javax.swing.JButton Exit;
    private javax.swing.JPasswordField Full_ConfirmPassword;
    private javax.swing.JTextField Full_Email;
    private javax.swing.JTextField Full_Password;
    private javax.swing.JTextField Full_Phone;
    private javax.swing.JTextField Full_Username;
    private javax.swing.JButton Go_Back;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Phone_Number;
    private javax.swing.JLabel Pink_Bar;
    private javax.swing.JButton Update_Email;
    private javax.swing.JButton Update_Password;
    private javax.swing.JButton Update_PhoneNumber;
    private javax.swing.JButton Update_Username;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel White_Background;
    private javax.swing.JButton logo;
    // End of variables declaration//GEN-END:variables
}
