/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.myproject.Interfaces;

import com.myproject.swproject.DBConnection;
import com.myproject.swproject.Item;
import com.myproject.swproject.Item.ItemStatus;
import com.myproject.swproject.UserSession;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Deema
 */
public class Home extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Home.class.getName());

    /**
     * Creates new form Home
     */
    
    private int userId = UserSession.getUserId();
    private ArrayList<Item> userItems = new ArrayList<>() ;
    public Home() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/Logo.png")).getImage());
        this.setSize(1020, 670);
        this.setLocationRelativeTo(null);
        
        // ====== MAKE USER_ITEMS USE VERTICAL BOX-LAYOUT ======
        User_Items.setLayout(new javax.swing.BoxLayout(User_Items, javax.swing.BoxLayout.Y_AXIS));
        loadUserItems();
        // Refresh UI
        User_Items.revalidate();
        User_Items.repaint();
    }
    
private void loadUserItems() {
    try {
        userItems = Item.getItemsForSpecificUser(userId);

        User_Items.removeAll();// Clear old UI components

        for (Item item : userItems) {
            ItemStatus status = item.getStatus();
            if (status != ItemStatus.APPROVED &&
                status != ItemStatus.REQUESTED &&
                status != ItemStatus.COMPLETED) {
                continue;
            }

            addItemCard(item);
        }

        User_Items.revalidate();
        User_Items.repaint();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error loading items: " + e.getMessage());
    }
}
   

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        User_Items = new javax.swing.JPanel();
        Home = new javax.swing.JLabel();
        logo = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Home_Button = new javax.swing.JButton();
        Searsh = new javax.swing.JButton();
        Upload = new javax.swing.JButton();
        Message = new javax.swing.JButton();
        Profile_Buttton = new javax.swing.JButton();
        Pink_Bar = new javax.swing.JLabel();
        Menu_Bar = new javax.swing.JLabel();
        White_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        getContentPane().setLayout(null);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        User_Items.setBackground(new java.awt.Color(255, 255, 255));
        User_Items.setLayout(null);
        jScrollPane1.setViewportView(User_Items);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 110, 980, 380);

        Home.setFont(new java.awt.Font("Lucida Fax", 3, 36)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 102, 102));
        Home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Home.setText("Your Donations");
        getContentPane().add(Home);
        Home.setBounds(390, 30, 320, 43);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink_logo.png"))); // NOI18N
        logo.setBorder(null);
        logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoActionPerformed(evt);
            }
        });
        getContentPane().add(logo);
        logo.setBounds(0, 0, 130, 100);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Exit.png"))); // NOI18N
        Exit.setBorder(null);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(870, 10, 100, 70);

        Home_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Home.png"))); // NOI18N
        Home_Button.setBorder(null);
        Home_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Home_Button);
        Home_Button.setBounds(30, 520, 100, 100);

        Searsh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Search.png"))); // NOI18N
        Searsh.setBorder(null);
        Searsh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearshActionPerformed(evt);
            }
        });
        getContentPane().add(Searsh);
        Searsh.setBounds(220, 520, 100, 100);

        Upload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Upload.png"))); // NOI18N
        Upload.setBorder(null);
        Upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadActionPerformed(evt);
            }
        });
        getContentPane().add(Upload);
        Upload.setBounds(410, 520, 100, 100);

        Message.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Message.png"))); // NOI18N
        Message.setBorder(null);
        Message.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MessageActionPerformed(evt);
            }
        });
        getContentPane().add(Message);
        Message.setBounds(620, 530, 110, 80);

        Profile_Buttton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Profile.png"))); // NOI18N
        Profile_Buttton.setBorder(null);
        Profile_Buttton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Profile_ButttonActionPerformed(evt);
            }
        });
        getContentPane().add(Profile_Buttton);
        Profile_Buttton.setBounds(830, 520, 100, 100);

        Pink_Bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink.png"))); // NOI18N
        getContentPane().add(Pink_Bar);
        Pink_Bar.setBounds(0, 0, 1000, 100);

        Menu_Bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink.png"))); // NOI18N
        getContentPane().add(Menu_Bar);
        Menu_Bar.setBounds(0, 520, 1000, 110);

        White_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/White.png"))); // NOI18N
        White_Background.setToolTipText("");
        getContentPane().add(White_Background);
        White_Background.setBounds(0, 0, 1000, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoActionPerformed
        // TODO add your handling code here:
        About_Us about = new About_Us();
        about.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed

        Welcome_Page newPage = new Welcome_Page();
        newPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void Home_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home_ButtonActionPerformed
        // TODO add your handling code here:
        Home newPage = new Home();
        newPage.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_Home_ButtonActionPerformed

    private void SearshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearshActionPerformed
        // TODO add your handling code here:
        Search newPage = new Search();
        newPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SearshActionPerformed

    private void UploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadActionPerformed
        // TODO add your handling code here:
        Upload newPage = new Upload();
        newPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_UploadActionPerformed

    private void MessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MessageActionPerformed
        // TODO add your handling code here:
        Notifications newPage = new Notifications();
        newPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MessageActionPerformed

    private void Profile_ButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile_ButttonActionPerformed
        // TODO add your handling code here:
        Profile newPage = new Profile();
        newPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Profile_ButttonActionPerformed
    
    
    //*** ITEM CARD CREATOR METHOD ***
    private void addItemCard(Item item) {

        JPanel card = new JPanel();
        card.setLayout(null);
        card.setPreferredSize(new java.awt.Dimension(900, 180));
        card.setMaximumSize(new java.awt.Dimension(900, 180));
        card.setBackground(new java.awt.Color(255, 245, 245));

        // Item image
        JLabel photo = new JLabel();
        photo.setBounds(20, 20, 130, 130);
        if (item.getImageUrl() != null) {
           ImageIcon icon = new ImageIcon(item.getImageUrl());
           Image scaled = icon.getImage().getScaledInstance(130, 130, Image.SCALE_SMOOTH);
           photo.setIcon(new ImageIcon(scaled));
        } else {
           photo.setText("No Image");
        }
        card.add(photo);

        // Item Title
        JLabel title = new JLabel(item.getTitle());
        title.setBounds(170, 20, 330, 30);
        title.setFont(new java.awt.Font("Verdana", 1, 18));
        card.add(title);

        // Details
        JLabel desc = new JLabel("<html>" + item.getDescription() + "</html>");
        desc.setBounds(170, 55, 400, 40);
        card.add(desc);

        // Item type
        JLabel type = new JLabel("Item Type: " + item.getItemType());
        type.setBounds(170, 100, 300, 20);
        card.add(type);
        
        // Item Condition
        JLabel condition = new JLabel("Condition: " + item.getItemCondition());
        condition.setBounds(170, 130, 300, 20);
        card.add(condition);

       //Item Status
      ItemStatus status = item.getStatus();

        if (status == ItemStatus.APPROVED) {
        //Edit button
        JButton editBtn = new JButton("Edit");
        editBtn.setBounds(700, 30, 120, 40);
        editBtn.setBackground(new java.awt.Color(229, 170, 58));
        editBtn.setForeground(new java.awt.Color(102, 51, 0));
        editBtn.setFont(new java.awt.Font("Verdana", java.awt.Font.BOLD, 16));

        editBtn.addActionListener(e -> {
            Edit_item editPage = new Edit_item(item.getItemId());
            editPage.setVisible(true);
            this.dispose();
        });

        card.add(editBtn);

        //Delete button
        JButton deleteBtn = new JButton("Delete");
        deleteBtn.setBounds(700, 90, 120, 40);
        deleteBtn.setBackground(new java.awt.Color(255, 100, 100));
        deleteBtn.setForeground(new java.awt.Color(90, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Verdana", java.awt.Font.BOLD, 16));

        deleteBtn.addActionListener(e -> deleteItem(item.getItemId(), card));

        card.add(deleteBtn);

    } else {
        //only a Status label
        JLabel stateLabel = new JLabel("Status: " + status);
        stateLabel.setBounds(700, 60, 150, 40);
        stateLabel.setFont(new java.awt.Font("Verdana", 1, 10));
        stateLabel.setForeground(new java.awt.Color(120, 0, 0));
        card.add(stateLabel);
    }

    //spacer
    JPanel spacer = new JPanel();
    spacer.setPreferredSize(new java.awt.Dimension(10, 10));
    spacer.setOpaque(false);

    User_Items.add(card);
    User_Items.add(spacer);
    }
    
    private void deleteItem(int itemId, JPanel card) {

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this item?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) return;

    try (Connection con = DBConnection.getConnection()) {

        String sql = "DELETE FROM Items WHERE item_id = ?";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setInt(1, itemId);
        ps.executeUpdate();

        JOptionPane.showMessageDialog(this, "Item deleted successfully!");

        User_Items.remove(card);
        User_Items.revalidate();
        User_Items.repaint();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error deleting item: " + e.getMessage());
    }
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Home().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Home;
    private javax.swing.JButton Home_Button;
    private javax.swing.JLabel Menu_Bar;
    private javax.swing.JButton Message;
    private javax.swing.JLabel Pink_Bar;
    private javax.swing.JButton Profile_Buttton;
    private javax.swing.JButton Searsh;
    private javax.swing.JButton Upload;
    private javax.swing.JPanel User_Items;
    private javax.swing.JLabel White_Background;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logo;
    // End of variables declaration//GEN-END:variables

}
