/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.myproject.Interfaces;

import com.myproject.swproject.DBConnection;
import com.myproject.swproject.ValidationUtils;
import com.myproject.swproject.UserSession;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Shahad
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());
    private String selectedUserType; // admin or  customer
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/Logo.png")).getImage());
        this.setSize(1020, 670);
        this.setLocationRelativeTo(null); 
        this.selectedUserType = UserSession.getselectedUserType();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JLabel();
        Create_Account = new javax.swing.JButton();
        Have_Account = new javax.swing.JLabel();
        Gray_Bar = new javax.swing.JLabel();
        Login_Button = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        logo = new javax.swing.JButton();
        Pink_Bar = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        Full_Email = new javax.swing.JTextField();
        Forget = new javax.swing.JButton();
        Full_Password = new javax.swing.JPasswordField();
        White_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setPreferredSize(new java.awt.Dimension(1440, 1038));
        getContentPane().setLayout(null);

        Login.setFont(new java.awt.Font("Lucida Fax", 3, 36)); // NOI18N
        Login.setForeground(new java.awt.Color(255, 102, 102));
        Login.setText("Login");
        getContentPane().add(Login);
        Login.setBounds(430, 30, 110, 43);

        Create_Account.setBackground(new java.awt.Color(216, 216, 216));
        Create_Account.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        Create_Account.setForeground(new java.awt.Color(204, 102, 0));
        Create_Account.setText("Create an account");
        Create_Account.setPreferredSize(new java.awt.Dimension(1440, 1038));
        Create_Account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Create_AccountActionPerformed(evt);
            }
        });
        getContentPane().add(Create_Account);
        Create_Account.setBounds(540, 550, 190, 40);

        Have_Account.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        Have_Account.setForeground(new java.awt.Color(102, 102, 102));
        Have_Account.setText("You don't have an account?");
        getContentPane().add(Have_Account);
        Have_Account.setBounds(250, 560, 230, 20);

        Gray_Bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Gray.png"))); // NOI18N
        getContentPane().add(Gray_Bar);
        Gray_Bar.setBounds(0, 540, 1000, 100);

        Login_Button.setBackground(new java.awt.Color(229, 170, 58));
        Login_Button.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        Login_Button.setForeground(new java.awt.Color(102, 51, 0));
        Login_Button.setText("Login");
        Login_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Login_Button);
        Login_Button.setBounds(540, 430, 180, 60);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Exit.png"))); // NOI18N
        Exit.setBorder(null);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(870, 10, 100, 70);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink_logo.png"))); // NOI18N
        logo.setBorder(null);
        logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoActionPerformed(evt);
            }
        });
        getContentPane().add(logo);
        logo.setBounds(0, 0, 130, 100);

        Pink_Bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink.png"))); // NOI18N
        getContentPane().add(Pink_Bar);
        Pink_Bar.setBounds(0, 0, 1000, 100);

        Email.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Email.setText("Email:");
        getContentPane().add(Email);
        Email.setBounds(170, 210, 100, 43);

        Password.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Password.setText("Password:");
        getContentPane().add(Password);
        Password.setBounds(170, 300, 130, 43);

        Full_Email.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        Full_Email.setForeground(new java.awt.Color(153, 153, 153));
        Full_Email.setText("Please enter your Email");
        getContentPane().add(Full_Email);
        Full_Email.setBounds(350, 210, 500, 40);

        Forget.setFont(new java.awt.Font("Segoe UI Semibold", 2, 14)); // NOI18N
        Forget.setForeground(new java.awt.Color(153, 204, 255));
        Forget.setText("Forgot Password?");
        Forget.setBorder(null);
        Forget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForgetActionPerformed(evt);
            }
        });
        getContentPane().add(Forget);
        Forget.setBounds(325, 450, 170, 20);

        Full_Password.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        Full_Password.setText("Please enter your Password");
        getContentPane().add(Full_Password);
        Full_Password.setBounds(350, 300, 500, 40);

        White_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/White.png"))); // NOI18N
        getContentPane().add(White_Background);
        White_Background.setBounds(0, 0, 1000, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        Welcome_Page newPage = new Welcome_Page();
        newPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void Login_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_ButtonActionPerformed
   String email = Full_Email.getText();
    String password = new String(Full_Password.getPassword());

    // Check if fields are empty
    if (email.isEmpty() || password.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Please enter email and password.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
  // Validate email and password
        if (!ValidationUtils.isValidEmail(email)) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email address.", 
                    "Invalid Email", JOptionPane.ERROR_MESSAGE);
            return;
        }

      
        if (!ValidationUtils.isValidPassword(password)) {
            JOptionPane.showMessageDialog(this,
                "Password must be at least 8 characters, include a capital letter, "
                        + "a number, and a special character.",
                "Invalid Password",
                JOptionPane.ERROR_MESSAGE);
            return;
        }

    
    // Connect to the database
    try (Connection con = DBConnection.getConnection()) { 
        if (con == null) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Database connection failed.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        String sql = "SELECT * FROM Users WHERE email = ? AND password = ? AND is_active = TRUE";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, email);
        pst.setString(2, password);

        ResultSet rs = pst.executeQuery();

    if (rs.next()) {
//  Check if the user type matches the selection.
    String userType = rs.getString("user_type");

    if (!userType.equalsIgnoreCase(selectedUserType)) {
        JOptionPane.showMessageDialog(this,
            "User type does not match the selection on Welcome Page.",
            "Login Error",
            JOptionPane.ERROR_MESSAGE);
        return;
          }


    JOptionPane.showMessageDialog(this, "Login successful!");

 // Fetch full user data
    int userId = rs.getInt("user_id");
    UserSession.setUserId(userId);
   // Check the user type and open the appropriate dashboard
    if (userType.equalsIgnoreCase("admin")) {
   // If user is admin, open Admin Dashboard
        Manage_Items adminPage =
                new Manage_Items();

        adminPage.setVisible(true);

    } else {
 // If user is customer, open Customer Dashboard 
        Home customerPage =
                new Home();

        customerPage.setVisible(true);
    }
// Close the login window after successful login
    this.dispose();


        } else {
          // User not found or email/password incorrect
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Email or password is incorrect or Account is inactive.",
                    "Login Failed",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
// Handle any exceptions 
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_Login_ButtonActionPerformed

    private void Create_AccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Create_AccountActionPerformed
        Sign_Up newPage = new Sign_Up();
        newPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Create_AccountActionPerformed

    private void logoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoActionPerformed
        // TODO add your handling code here:
        About_Us about = new About_Us(); 
        about.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_logoActionPerformed

    private void ForgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgetActionPerformed
        // TODO add your handling code here:
        Reset_Password  ResetPage = new Reset_Password(); 
        ResetPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ForgetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Create_Account;
    private javax.swing.JLabel Email;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Forget;
    private javax.swing.JTextField Full_Email;
    private javax.swing.JPasswordField Full_Password;
    private javax.swing.JLabel Gray_Bar;
    private javax.swing.JLabel Have_Account;
    private javax.swing.JLabel Login;
    private javax.swing.JButton Login_Button;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Pink_Bar;
    private javax.swing.JLabel White_Background;
    private javax.swing.JButton logo;
    // End of variables declaration//GEN-END:variables
}
