/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.myproject.Interfaces;
import com.myproject.swproject.DBConnection;
import com.myproject.swproject.UserSession;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shoug
 */
public class Manage_Customers extends javax.swing.JFrame {

    /**
     * Creates new form Customers
     */
    private int userId;
    public Manage_Customers() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/Logo.png")).getImage());
        this.setSize(1020, 670);
        this.setLocationRelativeTo(null); 
        this.userId = UserSession.getUserId(); 
        loadCustomersTable(); 
    }
    

private void loadCustomersTable() {
    String[] columns = {"user_id", "username", "email", "password", "phone", "location"};
    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(columns);

    try (Connection conn = DBConnection.getConnection()) {
        String query = "SELECT user_id, username, email, password, phone, "
                + "location FROM Users WHERE user_type = 'customer'" +
                "AND is_active = TRUE";
        PreparedStatement ps = conn.prepareStatement(query);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            int userId = rs.getInt("user_id");
            String username = rs.getString("username");
            String email = rs.getString("email");
            String password = rs.getString("password");
            String phone = rs.getString("phone");
            String location = rs.getString("location");

            model.addRow(new Object[]{userId, username, email, password, phone,location});
        }

        jTable2.setModel(model);

    } catch (SQLException e) {
        e.printStackTrace();
        System.out.println("Error loading customers: " + e.getMessage());
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JButton();
        Admin = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        Pink_Bar = new javax.swing.JLabel();
        Admin3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Reports = new javax.swing.JButton();
        Manage_Customers = new javax.swing.JButton();
        Profile_Buttton = new javax.swing.JButton();
        Items = new javax.swing.JButton();
        Menu_Bar = new javax.swing.JLabel();
        White_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Customers");
        getContentPane().setLayout(null);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink_logo.png"))); // NOI18N
        logo.setBorder(null);
        logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoActionPerformed(evt);
            }
        });
        getContentPane().add(logo);
        logo.setBounds(10, 0, 130, 100);

        Admin.setFont(new java.awt.Font("Lucida Fax", 3, 36)); // NOI18N
        Admin.setForeground(new java.awt.Color(255, 102, 102));
        Admin.setText("Manage Customers");
        getContentPane().add(Admin);
        Admin.setBounds(300, 30, 370, 43);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Exit.png"))); // NOI18N
        Exit.setBorder(null);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(880, 10, 100, 70);

        Pink_Bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink.png"))); // NOI18N
        getContentPane().add(Pink_Bar);
        Pink_Bar.setBounds(0, 0, 1000, 100);

        Admin3.setBackground(new java.awt.Color(229, 170, 58));
        Admin3.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        Admin3.setForeground(new java.awt.Color(102, 51, 0));
        Admin3.setText("Delete Customer");
        Admin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin3ActionPerformed(evt);
            }
        });
        getContentPane().add(Admin3);
        Admin3.setBounds(720, 290, 220, 50);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Username", "Email", "Password", "Phone", "Type", "Active"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 140, 670, 330);

        Reports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Report.png"))); // NOI18N
        Reports.setBorder(null);
        Reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportsActionPerformed(evt);
            }
        });
        getContentPane().add(Reports);
        Reports.setBounds(610, 520, 100, 100);

        Manage_Customers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Manage_Customers.png"))); // NOI18N
        Manage_Customers.setBorder(null);
        Manage_Customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manage_CustomersActionPerformed(evt);
            }
        });
        getContentPane().add(Manage_Customers);
        Manage_Customers.setBounds(310, 520, 120, 100);

        Profile_Buttton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Profile.png"))); // NOI18N
        Profile_Buttton.setBorder(null);
        Profile_Buttton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Profile_ButttonActionPerformed(evt);
            }
        });
        getContentPane().add(Profile_Buttton);
        Profile_Buttton.setBounds(850, 520, 100, 100);

        Items.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Items.png"))); // NOI18N
        Items.setBorder(null);
        Items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemsActionPerformed(evt);
            }
        });
        getContentPane().add(Items);
        Items.setBounds(60, 530, 100, 90);

        Menu_Bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink.png"))); // NOI18N
        getContentPane().add(Menu_Bar);
        Menu_Bar.setBounds(0, 520, 1000, 110);

        White_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/White.png"))); // NOI18N
        White_Background.setToolTipText("");
        getContentPane().add(White_Background);
        White_Background.setBounds(0, 0, 1000, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoActionPerformed
        // TODO add your handling code here:
        About_Us about = new About_Us();
        about.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed

        Welcome_Page newPage = new Welcome_Page();
        newPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void Admin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin3ActionPerformed
        // TODO add your handling code here
        int selectedRow = jTable2.getSelectedRow();
    
    if (selectedRow != -1) {
        int userId = (int) jTable2.getValueAt(selectedRow, 0);

        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "Are you sure you want to delete this customer?", 
            "Confirm Delete", 
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try (Connection conn = DBConnection.getConnection()) {
                String sql = "UPDATE Users SET is_active = FALSE WHERE user_id = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setInt(1, userId);
                ps.executeUpdate();

                
                loadCustomersTable();

                javax.swing.JOptionPane.showMessageDialog(this, "Customer deactivated successfully!");
            } catch (SQLException e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Error deleting customer: " + e.getMessage());
            }
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a customer first!");
    }
    }//GEN-LAST:event_Admin3ActionPerformed

    private void ReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportsActionPerformed
        Manage_Reports reportsPage = new Manage_Reports();
        reportsPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReportsActionPerformed

    private void Manage_CustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_CustomersActionPerformed
       // this page
    }//GEN-LAST:event_Manage_CustomersActionPerformed

    private void Profile_ButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile_ButttonActionPerformed
        // TODO add your handling code here:
        Admin_Profile newPage = new Admin_Profile();
        newPage.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_Profile_ButttonActionPerformed

    private void ItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemsActionPerformed
       
        Manage_Items itemsPage = new Manage_Items();
        itemsPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ItemsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new  Manage_Customers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin;
    private javax.swing.JButton Admin3;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Items;
    private javax.swing.JButton Manage_Customers;
    private javax.swing.JLabel Menu_Bar;
    private javax.swing.JLabel Pink_Bar;
    private javax.swing.JButton Profile_Buttton;
    private javax.swing.JButton Reports;
    private javax.swing.JLabel White_Background;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton logo;
    // End of variables declaration//GEN-END:variables
}
