/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.myproject.Interfaces;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import com.myproject.swproject.DBConnection; 
import com.myproject.swproject.NotificationManage;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;



/**
 *
 * @author Shoug
 */
public class Manage_Reports extends javax.swing.JFrame {

    /**
     * Creates new form Reports
     */
    public Manage_Reports() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/Logo.png")).getImage());
        this.setSize(1020, 670);
        this.setLocationRelativeTo(null); 
        loadReportsTable();
    }
    
public void loadReportsTable() {

        String[] columns = {"donation_id", "donor_id", "donee_id", "item_id", "state", "notes"};
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(columns);

        try (Connection conn = DBConnection.getConnection()) {

            String query =
                "SELECT donation_id, donor_id, donee_id, item_id, state, notes " +
                "FROM Donation_Reports";

            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {

                int donationId = rs.getInt("donation_id");
                int donorId = rs.getInt("donor_id");
                int doneeId = rs.getInt("donee_id");
                int itemId = rs.getInt("item_id");
                String state = rs.getString("state");
                String notes = rs.getString("notes");

                model.addRow(new Object[]{donationId, donorId, doneeId, itemId, state, notes});
            }

            jTable1.setModel(model);

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JButton();
        Admin = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        Pink_Bar = new javax.swing.JLabel();
        update_status = new javax.swing.JButton();
        add_notes = new javax.swing.JButton();
        delete_report = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Reports = new javax.swing.JButton();
        Manage_Customers = new javax.swing.JButton();
        Profile_Buttton = new javax.swing.JButton();
        Items = new javax.swing.JButton();
        Menu_Bar = new javax.swing.JLabel();
        White_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Reports");
        getContentPane().setLayout(null);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink_logo.png"))); // NOI18N
        logo.setBorder(null);
        logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoActionPerformed(evt);
            }
        });
        getContentPane().add(logo);
        logo.setBounds(10, 0, 130, 100);

        Admin.setFont(new java.awt.Font("Lucida Fax", 3, 36)); // NOI18N
        Admin.setForeground(new java.awt.Color(255, 102, 102));
        Admin.setText("Reports");
        getContentPane().add(Admin);
        Admin.setBounds(430, 30, 160, 43);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Exit.png"))); // NOI18N
        Exit.setBorder(null);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(880, 10, 100, 70);

        Pink_Bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink.png"))); // NOI18N
        getContentPane().add(Pink_Bar);
        Pink_Bar.setBounds(0, 0, 1000, 100);

        update_status.setBackground(new java.awt.Color(229, 170, 58));
        update_status.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        update_status.setForeground(new java.awt.Color(102, 51, 0));
        update_status.setText("Update Status");
        update_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_statusActionPerformed(evt);
            }
        });
        getContentPane().add(update_status);
        update_status.setBounds(720, 200, 180, 50);

        add_notes.setBackground(new java.awt.Color(229, 170, 58));
        add_notes.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        add_notes.setForeground(new java.awt.Color(102, 51, 0));
        add_notes.setText("Add Notes");
        add_notes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_notesActionPerformed(evt);
            }
        });
        getContentPane().add(add_notes);
        add_notes.setBounds(720, 280, 180, 50);

        delete_report.setBackground(new java.awt.Color(229, 170, 58));
        delete_report.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        delete_report.setForeground(new java.awt.Color(102, 51, 0));
        delete_report.setText("Delete Report");
        delete_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_reportActionPerformed(evt);
            }
        });
        getContentPane().add(delete_report);
        delete_report.setBounds(720, 360, 180, 50);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "report_id", "reporter_id", "reported_item_id", "report_type", "description", "status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 150, 580, 310);

        Reports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Report.png"))); // NOI18N
        Reports.setBorder(null);
        Reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportsActionPerformed(evt);
            }
        });
        getContentPane().add(Reports);
        Reports.setBounds(610, 520, 100, 100);

        Manage_Customers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Manage_Customers.png"))); // NOI18N
        Manage_Customers.setBorder(null);
        Manage_Customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manage_CustomersActionPerformed(evt);
            }
        });
        getContentPane().add(Manage_Customers);
        Manage_Customers.setBounds(310, 520, 120, 100);

        Profile_Buttton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Profile.png"))); // NOI18N
        Profile_Buttton.setBorder(null);
        Profile_Buttton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Profile_ButttonActionPerformed(evt);
            }
        });
        getContentPane().add(Profile_Buttton);
        Profile_Buttton.setBounds(850, 520, 100, 100);

        Items.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Items.png"))); // NOI18N
        Items.setBorder(null);
        Items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemsActionPerformed(evt);
            }
        });
        getContentPane().add(Items);
        Items.setBounds(60, 530, 100, 90);

        Menu_Bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink.png"))); // NOI18N
        getContentPane().add(Menu_Bar);
        Menu_Bar.setBounds(0, 520, 1000, 110);

        White_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/White.png"))); // NOI18N
        White_Background.setToolTipText("");
        getContentPane().add(White_Background);
        White_Background.setBounds(0, 0, 1000, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoActionPerformed
        // TODO add your handling code here:
        About_Us about = new About_Us();
        about.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed

        Welcome_Page newPage = new Welcome_Page();
        newPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void update_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_statusActionPerformed

int row = jTable1.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a report!");
        return;
    }

    int donationId = (int) jTable1.getValueAt(row, 0);
    int donorId = (int) jTable1.getValueAt(row, 1);
    int doneeId = (int) jTable1.getValueAt(row, 2);
    int itemId = (int) jTable1.getValueAt(row, 3);
    String currentState = (String) jTable1.getValueAt(row, 5);

    String[] states = {"in_progress", "completed", "cancelled"};

    JComboBox<String> combo = new JComboBox<>(states);
    combo.setSelectedItem(currentState);

    int result = JOptionPane.showConfirmDialog(
            this,
            combo,
            "Select new state",
            JOptionPane.OK_CANCEL_OPTION
    );

    if (result != JOptionPane.OK_OPTION) {
        return;
    }

    String newState = (String) combo.getSelectedItem();

    try (Connection conn = DBConnection.getConnection()) {

        conn.setAutoCommit(false);
        
        String updateReportSql =
                "UPDATE Donation_Reports SET state = ? WHERE donation_id = ?";
        try (PreparedStatement ps = conn.prepareStatement(updateReportSql)) {
            ps.setString(1, newState);
            ps.setInt(2, donationId);
            ps.executeUpdate();
        }

        //If donation completed → update item state
        if ("completed".equals(newState)) {
            String updateItemSql =
                    "UPDATE Items SET status = 'completed' WHERE item_id = ?";
            try (PreparedStatement ps = conn.prepareStatement(updateItemSql)) {
                ps.setInt(1, itemId);
                ps.executeUpdate();
             NotificationManage.sendDonationCompletedNotification(conn, donorId, itemId);
             NotificationManage.sendDonationCompletedNotification(conn, doneeId, itemId);
            }
        }

        conn.commit();

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error updating status!");
    }

    loadReportsTable();
    }//GEN-LAST:event_update_statusActionPerformed

    private void delete_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_reportActionPerformed

    int row = jTable1.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a report!");
        return;
    }

    int donationId = (int) jTable1.getValueAt(row, 0);
    String state = (String) jTable1.getValueAt(row, 5);

    // only delete cancelled donations
    if (!"cancelled".equalsIgnoreCase(state)) {
        JOptionPane.showMessageDialog(this,
                "You can delete a report only if the donation is cancelled.",
                "Delete Not Allowed",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
            this,
            "Delete this cancelled donation report?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION)
        return;

    try (Connection conn = DBConnection.getConnection()) {
        String sql = "DELETE FROM Donation_Reports WHERE donation_id = ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, donationId);
        ps.executeUpdate();
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error deleting report!");
    }

    loadReportsTable();
 
    }//GEN-LAST:event_delete_reportActionPerformed

    private void ReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportsActionPerformed
        // this page
    }//GEN-LAST:event_ReportsActionPerformed

    private void Manage_CustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_CustomersActionPerformed
        Manage_Customers customersPage = new  Manage_Customers();
        customersPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Manage_CustomersActionPerformed

    private void Profile_ButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile_ButttonActionPerformed
        // TODO add your handling code here:
        Admin_Profile newPage = new Admin_Profile();
        newPage.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_Profile_ButttonActionPerformed

    private void ItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemsActionPerformed

        Manage_Items itemsPage = new Manage_Items();
        itemsPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ItemsActionPerformed

    private void add_notesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_notesActionPerformed
            int row = jTable1.getSelectedRow();

    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a report!");
        return;
    }

    int donationId = (int) jTable1.getValueAt(row, 0);

    JTextArea textArea = new JTextArea(5, 30);
    textArea.setLineWrap(true);
    textArea.setWrapStyleWord(true);

    int result = JOptionPane.showConfirmDialog(
            this,
            new JScrollPane(textArea),
            "Add / Update Notes",
            JOptionPane.OK_CANCEL_OPTION
    );

    if (result != JOptionPane.OK_OPTION)
        return;

    String notes = textArea.getText().trim();

    try (Connection conn = DBConnection.getConnection()) {
        String sql = "UPDATE Donation_Reports SET notes = ? WHERE donation_id = ?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, notes);
        ps.setInt(2, donationId);
        ps.executeUpdate();
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error updating notes!");
    }

    loadReportsTable();
        
    }//GEN-LAST:event_add_notesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_Reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Items;
    private javax.swing.JButton Manage_Customers;
    private javax.swing.JLabel Menu_Bar;
    private javax.swing.JLabel Pink_Bar;
    private javax.swing.JButton Profile_Buttton;
    private javax.swing.JButton Reports;
    private javax.swing.JLabel White_Background;
    private javax.swing.JButton add_notes;
    private javax.swing.JButton delete_report;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logo;
    private javax.swing.JButton update_status;
    // End of variables declaration//GEN-END:variables
}