/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.myproject.Interfaces;

import com.myproject.swproject.DBConnection;
import com.myproject.swproject.NotificationManage;
import com.myproject.swproject.UserSession;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shoug
 */
public class Manage_Items extends javax.swing.JFrame {

    /**
     * Creates new form Manage_Items
     */
    private int userId;
    public Manage_Items() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/Logo.png")).getImage());
        this.setSize(1020, 670);
        this.setLocationRelativeTo(null);
        this.userId = UserSession.getUserId(); 
        loadItemsTable();
    }
    
    public void loadItemsTable() {
    String[] columns = {"item_id", "user_id", "title", "description", "item_type", "item_condition", "status", "image_url"};
    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(columns);

    try (Connection conn = DBConnection.getConnection()) {
        String query = "SELECT item_id, user_id, title, description, item_type, item_condition, status, image_url FROM Items";
        PreparedStatement ps = conn.prepareStatement(query);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            int itemId = rs.getInt("item_id");
            int userId = rs.getInt("user_id");
            String title = rs.getString("title");
            String description = rs.getString("description");
            String itemType = rs.getString("item_type");
            String itemCondition = rs.getString("item_condition");
            String status = rs.getString("status");
            String imageUrl = rs.getString("image_url");

            model.addRow(new Object[]{itemId, userId, title, description, itemType, itemCondition, status, imageUrl});
        }

        jTable1.setModel(model);

    } catch (SQLException e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Error loading items from database!");
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JButton();
        Admin = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        Pink_Bar = new javax.swing.JLabel();
        Admin3 = new javax.swing.JButton();
        Admin4 = new javax.swing.JButton();
        Admin5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Reports1 = new javax.swing.JButton();
        Manage_Customers = new javax.swing.JButton();
        Profile_Buttton = new javax.swing.JButton();
        Items = new javax.swing.JButton();
        Menu_Bar = new javax.swing.JLabel();
        White_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Items");
        getContentPane().setLayout(null);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink_logo.png"))); // NOI18N
        logo.setBorder(null);
        logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoActionPerformed(evt);
            }
        });
        getContentPane().add(logo);
        logo.setBounds(10, 0, 130, 100);

        Admin.setFont(new java.awt.Font("Lucida Fax", 3, 36)); // NOI18N
        Admin.setForeground(new java.awt.Color(255, 102, 102));
        Admin.setText("Items");
        getContentPane().add(Admin);
        Admin.setBounds(450, 30, 120, 43);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Exit.png"))); // NOI18N
        Exit.setBorder(null);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(880, 10, 100, 70);

        Pink_Bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink.png"))); // NOI18N
        getContentPane().add(Pink_Bar);
        Pink_Bar.setBounds(0, 0, 1000, 100);

        Admin3.setBackground(new java.awt.Color(229, 170, 58));
        Admin3.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        Admin3.setForeground(new java.awt.Color(102, 51, 0));
        Admin3.setText("Approve Item");
        Admin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin3ActionPerformed(evt);
            }
        });
        getContentPane().add(Admin3);
        Admin3.setBounds(730, 200, 180, 50);

        Admin4.setBackground(new java.awt.Color(229, 170, 58));
        Admin4.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        Admin4.setForeground(new java.awt.Color(102, 51, 0));
        Admin4.setText("Reject Item");
        Admin4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin4ActionPerformed(evt);
            }
        });
        getContentPane().add(Admin4);
        Admin4.setBounds(730, 280, 180, 50);

        Admin5.setBackground(new java.awt.Color(229, 170, 58));
        Admin5.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        Admin5.setForeground(new java.awt.Color(102, 51, 0));
        Admin5.setText("Delete Item");
        Admin5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin5ActionPerformed(evt);
            }
        });
        getContentPane().add(Admin5);
        Admin5.setBounds(730, 360, 180, 50);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "item_id", "User_id", "Title", "Description", "Item_type", "Location", "Status", "Image_url"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 140, 630, 330);

        Reports1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Report.png"))); // NOI18N
        Reports1.setBorder(null);
        Reports1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reports1ActionPerformed(evt);
            }
        });
        getContentPane().add(Reports1);
        Reports1.setBounds(610, 520, 100, 100);

        Manage_Customers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Manage_Customers.png"))); // NOI18N
        Manage_Customers.setBorder(null);
        Manage_Customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manage_CustomersActionPerformed(evt);
            }
        });
        getContentPane().add(Manage_Customers);
        Manage_Customers.setBounds(310, 520, 120, 100);

        Profile_Buttton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Profile.png"))); // NOI18N
        Profile_Buttton.setBorder(null);
        Profile_Buttton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Profile_ButttonActionPerformed(evt);
            }
        });
        getContentPane().add(Profile_Buttton);
        Profile_Buttton.setBounds(850, 520, 100, 100);

        Items.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Items.png"))); // NOI18N
        Items.setBorder(null);
        Items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemsActionPerformed(evt);
            }
        });
        getContentPane().add(Items);
        Items.setBounds(60, 530, 100, 90);

        Menu_Bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink.png"))); // NOI18N
        getContentPane().add(Menu_Bar);
        Menu_Bar.setBounds(0, 520, 1000, 110);

        White_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/White.png"))); // NOI18N
        White_Background.setToolTipText("");
        getContentPane().add(White_Background);
        White_Background.setBounds(0, 0, 1000, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoActionPerformed
        // TODO add your handling code here:
        About_Us about = new About_Us();
        about.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed

        Welcome_Page newPage = new Welcome_Page();
        newPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void Admin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin3ActionPerformed
        // TODO add your handling code here
         int selectedRow = jTable1.getSelectedRow();
    if (selectedRow != -1) {
        int itemId = (int) jTable1.getValueAt(selectedRow, 0);

        try (Connection conn = DBConnection.getConnection()) {
            String sql = "UPDATE Items SET status = 'approved', approved_at = CURRENT_TIMESTAMP,"
                    + " approved_by = ? WHERE item_id = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, userId);
            ps.setInt(2, itemId);
            ps.executeUpdate();
            
            int ownerId = -1;
            String ownerSql = "SELECT user_id FROM Items WHERE item_id = ?";
            PreparedStatement ownerPs = conn.prepareStatement(ownerSql);
            ownerPs.setInt(1, itemId);
            ResultSet rs = ownerPs.executeQuery();

        if (rs.next()) {
            ownerId = rs.getInt("user_id");
            NotificationManage.sendItemApprovedNotification(conn,ownerId,itemId);
        }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        loadItemsTable();
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select an item first!");
    }
    }//GEN-LAST:event_Admin3ActionPerformed

    private void Admin4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin4ActionPerformed
        // TODO add your handling code here
        int selectedRow = jTable1.getSelectedRow();
    if (selectedRow != -1) {
        int itemId = (int) jTable1.getValueAt(selectedRow, 0);

        String reason = javax.swing.JOptionPane.showInputDialog(this, "Enter rejection reason:");
        if (reason != null && !reason.trim().isEmpty()) {
            try (Connection conn = DBConnection.getConnection()) {
                String sql = "UPDATE Items SET status = 'rejected', rejection_reason = ? WHERE item_id = ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setString(1, reason);
                ps.setInt(2, itemId);
                ps.executeUpdate();
                
                 int ownerId = -1;
                 String ownerSql = "SELECT user_id FROM Items WHERE item_id = ?";
              PreparedStatement ownerPs = conn.prepareStatement(ownerSql);
        ownerPs.setInt(1, itemId);
        ResultSet rs = ownerPs.executeQuery();

        if (rs.next()) {
            ownerId = rs.getInt("user_id");
                NotificationManage.sendItemRejectedNotification(conn, ownerId, itemId, reason); 
        }
        
            } catch (SQLException e) {
                e.printStackTrace();
            }
            loadItemsTable();
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select an item first!");
    }
    }//GEN-LAST:event_Admin4ActionPerformed

    private void Admin5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin5ActionPerformed
        // TODO add your handling code here
        int selectedRow = jTable1.getSelectedRow();
    if (selectedRow != -1) {
        int itemId = (int) jTable1.getValueAt(selectedRow, 0);
        String state = (String) jTable1.getValueAt(selectedRow, 6);
            
    // only delete rejected items
    if (!"rejected".equalsIgnoreCase(state)) {
        JOptionPane.showMessageDialog(this,
                "You can delete an item only if the itemm is rejected.",
                "Delete Not Allowed",
                JOptionPane.WARNING_MESSAGE);
        return;
    }
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to delete this item?", 
                "Confirm Delete", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try (Connection conn = DBConnection.getConnection()) {
                String sql = "DELETE FROM Items WHERE item_id= ?";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.setInt(1, itemId);
                ps.executeUpdate();
            } catch (SQLException e) {
                e.printStackTrace();
            }
            loadItemsTable();
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select an item first!");
    }
    }//GEN-LAST:event_Admin5ActionPerformed

    private void Reports1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reports1ActionPerformed
        Manage_Reports reportsPage = new Manage_Reports();
        reportsPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Reports1ActionPerformed

    private void Manage_CustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_CustomersActionPerformed
        Manage_Customers customersPage = new  Manage_Customers();
        customersPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Manage_CustomersActionPerformed

    private void Profile_ButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile_ButttonActionPerformed
        Admin_Profile newPage = new Admin_Profile();
        newPage.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_Profile_ButttonActionPerformed

    private void ItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemsActionPerformed
        // this page
    }//GEN-LAST:event_ItemsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Items.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_Items().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin;
    private javax.swing.JButton Admin3;
    private javax.swing.JButton Admin4;
    private javax.swing.JButton Admin5;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Items;
    private javax.swing.JButton Manage_Customers;
    private javax.swing.JLabel Menu_Bar;
    private javax.swing.JLabel Pink_Bar;
    private javax.swing.JButton Profile_Buttton;
    private javax.swing.JButton Reports;
    private javax.swing.JButton Reports1;
    private javax.swing.JLabel White_Background;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logo;
    // End of variables declaration//GEN-END:variables
}
