

package com.myproject.Interfaces;
import com.myproject.swproject.DBConnection;
import com.myproject.swproject.Notification;
import com.myproject.swproject.NotificationManage;
import com.myproject.swproject.UserSession;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Shoug
 */
public class Notifications extends javax.swing.JFrame {
    

    private int userId = UserSession.getUserId();
    private ArrayList<Notification> notifications = new ArrayList<>();

    public Notifications() {
    initComponents();
    this.setSize(1020, 670);
    this.setLocationRelativeTo(null);

    NotificationsPanel.setLayout(
        new javax.swing.BoxLayout(
            NotificationsPanel,
            javax.swing.BoxLayout.Y_AXIS
        )
    );

    loadNotifications("All");
}
private void loadNotifications(String filter) {

    try {
        NotificationsPanel.removeAll();

        if (filter.equalsIgnoreCase("All")) {
            notifications = new ArrayList<>(
                NotificationManage.getUserNotifications(userId)
            );
        } else if (filter.equalsIgnoreCase("Unread")) {
            notifications = new ArrayList<>(
                NotificationManage.getNotificationsByStatus(
                    userId, Notification.NotificationStatus.unread)
            );
        } else {
            notifications = new ArrayList<>(
                NotificationManage.getNotificationsByStatus(
                    userId, Notification.NotificationStatus.read)
            );
        }

        for (Notification n : notifications) {
            addNotificationCard(n);
        }

        NotificationsPanel.revalidate();
        NotificationsPanel.repaint();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this,
            "Error loading notifications: " + e.getMessage());
    }
}

private void addNotificationCard(Notification n) {

    JPanel card = new JPanel();
    card.setLayout(null);
    card.setPreferredSize(new java.awt.Dimension(900, 120));
    card.setMaximumSize(new java.awt.Dimension(900, 120));
    card.setBackground(
        n.getStatus() == Notification.NotificationStatus.unread
            ? new java.awt.Color(255, 245, 230)
            : new java.awt.Color(245, 245, 245)
    );

    // Type
    JLabel type = new JLabel(n.getType().name().replace("_", " "));
    type.setFont(new java.awt.Font("Verdana", 1, 14));
    type.setBounds(20, 10, 300, 20);
    card.add(type);

    // Message
    JLabel message = new JLabel("<html>" + n.getMessage() + "</html>");
    message.setBounds(20, 35, 600, 40);
    card.add(message);

    // Date
    JLabel date = new JLabel(n.getCreatedAt().toString());
    date.setFont(new java.awt.Font("Verdana", 0, 10));
    date.setBounds(20, 80, 250, 15);
    card.add(date);

    // Checkbox (Mark as read)
    JCheckBox readBox = new JCheckBox("Read");
    readBox.setBounds(750, 40, 100, 30);
    readBox.setSelected(n.getStatus() == Notification.NotificationStatus.read);

    readBox.addActionListener(e -> {
        try {
            NotificationManage.markAsRead(n.getNotificationId());
            n.setStatus(Notification.NotificationStatus.read);
            loadNotifications(
                (String) FilterComboBox.getSelectedItem()
            );
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,
                "Error updating notification");
        }
    });

    card.add(readBox);

    // spacer
    JPanel spacer = new JPanel();
    spacer.setPreferredSize(new java.awt.Dimension(10, 10));
    spacer.setOpaque(false);

    NotificationsPanel.add(card);
    NotificationsPanel.add(spacer);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JButton();
        Admin = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        Pink_Bar = new javax.swing.JLabel();
        FilterComboBox = new javax.swing.JComboBox<>();
        Upload_Button = new javax.swing.JButton();
        Message = new javax.swing.JButton();
        Profile_Buttton = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        Searsh = new javax.swing.JButton();
        filter1 = new javax.swing.JLabel();
        Menu_Bar = new javax.swing.JLabel();
        NotificationsPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Notifications");
        getContentPane().setLayout(null);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink_logo.png"))); // NOI18N
        logo.setBorder(null);
        logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoActionPerformed(evt);
            }
        });
        getContentPane().add(logo);
        logo.setBounds(10, 0, 130, 100);

        Admin.setFont(new java.awt.Font("Lucida Fax", 3, 36)); // NOI18N
        Admin.setForeground(new java.awt.Color(255, 102, 102));
        Admin.setText("Notifications");
        getContentPane().add(Admin);
        Admin.setBounds(380, 30, 260, 43);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Exit.png"))); // NOI18N
        Exit.setBorder(null);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(880, 10, 100, 70);

        Pink_Bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink.png"))); // NOI18N
        getContentPane().add(Pink_Bar);
        Pink_Bar.setBounds(0, 0, 1000, 100);

        FilterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Read", "Unread" }));
        FilterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilterComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(FilterComboBox);
        FilterComboBox.setBounds(500, 120, 140, 30);

        Upload_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Upload.png"))); // NOI18N
        Upload_Button.setBorder(null);
        Upload_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Upload_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Upload_Button);
        Upload_Button.setBounds(430, 520, 100, 100);

        Message.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Message.png"))); // NOI18N
        Message.setBorder(null);
        Message.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MessageActionPerformed(evt);
            }
        });
        getContentPane().add(Message);
        Message.setBounds(650, 530, 110, 80);

        Profile_Buttton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Profile.png"))); // NOI18N
        Profile_Buttton.setBorder(null);
        Profile_Buttton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Profile_ButttonActionPerformed(evt);
            }
        });
        getContentPane().add(Profile_Buttton);
        Profile_Buttton.setBounds(870, 520, 100, 100);

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Home.png"))); // NOI18N
        Home.setBorder(null);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        getContentPane().add(Home);
        Home.setBounds(20, 520, 100, 100);

        Searsh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Search.png"))); // NOI18N
        Searsh.setBorder(null);
        Searsh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearshActionPerformed(evt);
            }
        });
        getContentPane().add(Searsh);
        Searsh.setBounds(220, 520, 100, 100);

        filter1.setFont(new java.awt.Font("Lucida Fax", 3, 18)); // NOI18N
        filter1.setText("Filter Notifications");
        getContentPane().add(filter1);
        filter1.setBounds(310, 120, 180, 30);

        Menu_Bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink.png"))); // NOI18N
        getContentPane().add(Menu_Bar);
        Menu_Bar.setBounds(0, 520, 1000, 110);

        NotificationsPanel.setBackground(new java.awt.Color(255, 255, 255));
        NotificationsPanel.setLayout(null);
        getContentPane().add(NotificationsPanel);
        NotificationsPanel.setBounds(30, 180, 940, 310);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/White.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoActionPerformed
        // TODO add your handling code here:
        About_Us about = new About_Us();
        about.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        // فتح الصفحة الجديدة
        Welcome_Page newPage = new Welcome_Page();
        newPage.setVisible(true);

        // إغلاق الصفحة الحالية
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        Home newPage = new Home();
        newPage.setVisible(true);
        this.dispose();  // إغلاق الصفحة الحالية
    }//GEN-LAST:event_HomeActionPerformed

    private void SearshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearshActionPerformed
        // TODO add your handling code here:
        Search newPage = new Search();
        newPage.setVisible(true);
        this.dispose();  // إغلاق الصفحة الحالية 
    }//GEN-LAST:event_SearshActionPerformed

    private void Upload_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Upload_ButtonActionPerformed
        // TODO add your handling code here:
        Upload newPage = new Upload();
        newPage.setVisible(true);
        this.dispose();  // إغلاق الصفحة الحالية
    }//GEN-LAST:event_Upload_ButtonActionPerformed

    private void MessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MessageActionPerformed
        // TODO add your handling code here:
        Notifications newPage = new Notifications();
        newPage.setVisible(true);
        this.dispose();  // إغلاق الصفحة الحالية*/
    }//GEN-LAST:event_MessageActionPerformed

    private void Profile_ButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile_ButttonActionPerformed
        // TODO add your handling code here:
        Profile newPage = new Profile();
        newPage.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_Profile_ButttonActionPerformed

    private void FilterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilterComboBoxActionPerformed
        String selected = (String) FilterComboBox.getSelectedItem();
        loadNotifications(selected);
    }//GEN-LAST:event_FilterComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notifications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notifications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notifications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notifications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notifications().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin;
    private javax.swing.JButton Exit;
    private javax.swing.JComboBox<String> FilterComboBox;
    private javax.swing.JButton Home;
    private javax.swing.JLabel Menu_Bar;
    private javax.swing.JButton Message;
    private javax.swing.JPanel NotificationsPanel;
    private javax.swing.JLabel Pink_Bar;
    private javax.swing.JButton Profile_Buttton;
    private javax.swing.JButton Searsh;
    private javax.swing.JButton Upload_Button;
    private javax.swing.JLabel filter1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton logo;
    // End of variables declaration//GEN-END:variables
}
