/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.myproject.Interfaces;
import com.myproject.swproject.DBConnection;
import com.myproject.swproject.UserSession;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Deema
 */
public class Reset_Password extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Reset_Password.class.getName());
     private String selectedUserType;
    /**
     * Creates new form Reset_Password
     */
    public Reset_Password() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/Logo.png")).getImage());
        this.setSize(1020, 670);
        this.setLocationRelativeTo(null);
        this.selectedUserType = UserSession.getselectedUserType();
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JButton();
        Reset_Password = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        Email = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        Full_Email = new javax.swing.JTextField();
        Full_Password = new javax.swing.JPasswordField();
        Pink_Bar = new javax.swing.JLabel();
        Confirm_Password = new javax.swing.JLabel();
        Full_Password1 = new javax.swing.JTextField();
        Update_Password = new javax.swing.JButton();
        White_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink_logo.png"))); // NOI18N
        logo.setBorder(null);
        logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoActionPerformed(evt);
            }
        });
        getContentPane().add(logo);
        logo.setBounds(0, 0, 130, 100);

        Reset_Password.setFont(new java.awt.Font("Lucida Fax", 3, 36)); // NOI18N
        Reset_Password.setForeground(new java.awt.Color(255, 102, 102));
        Reset_Password.setText("Reset Password");
        getContentPane().add(Reset_Password);
        Reset_Password.setBounds(320, 30, 300, 43);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Exit.png"))); // NOI18N
        Exit.setBorder(null);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(870, 10, 100, 70);

        Email.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Email.setText("Email:");
        getContentPane().add(Email);
        Email.setBounds(90, 210, 100, 43);

        Password.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Password.setText("New Password:");
        getContentPane().add(Password);
        Password.setBounds(90, 300, 190, 43);

        Full_Email.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        Full_Email.setForeground(new java.awt.Color(153, 153, 153));
        Full_Email.setText("Please enter your Email");
        getContentPane().add(Full_Email);
        Full_Email.setBounds(350, 210, 500, 40);

        Full_Password.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        Full_Password.setText("Please enter your Password");
        getContentPane().add(Full_Password);
        Full_Password.setBounds(440, 390, 410, 40);

        Pink_Bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink.png"))); // NOI18N
        getContentPane().add(Pink_Bar);
        Pink_Bar.setBounds(0, 0, 1000, 100);

        Confirm_Password.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Confirm_Password.setText("Confirm New Password:");
        getContentPane().add(Confirm_Password);
        Confirm_Password.setBounds(90, 390, 300, 30);

        Full_Password1.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        Full_Password1.setForeground(new java.awt.Color(153, 153, 153));
        Full_Password1.setText("Please enter your Password");
        Full_Password1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Full_Password1ActionPerformed(evt);
            }
        });
        getContentPane().add(Full_Password1);
        Full_Password1.setBounds(350, 300, 500, 40);

        Update_Password.setBackground(new java.awt.Color(229, 170, 58));
        Update_Password.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        Update_Password.setForeground(new java.awt.Color(102, 51, 0));
        Update_Password.setText("Update");
        Update_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Update_Password);
        Update_Password.setBounds(540, 470, 180, 60);

        White_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/White.png"))); // NOI18N
        White_Background.setToolTipText("");
        getContentPane().add(White_Background);
        White_Background.setBounds(0, 0, 1000, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents
// Opens the About Us page when the logo is clicked
    private void logoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoActionPerformed
        // TODO add your handling code here:
        About_Us about = new About_Us();
        about.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoActionPerformed
// Returns to the Welcome page and closes the current window
    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
       
      
        Welcome_Page newPage = new Welcome_Page();
        newPage.setVisible(true);
       
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void Full_Password1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Full_Password1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Full_Password1ActionPerformed
// Main process for updating the password:
// - Validates fields
// - Confirms password match
// - Checks password strength
// - Connects to database and updates password
    private void Update_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_PasswordActionPerformed
     
        {                                         
    String email = Full_Email.getText().trim();
    String newPass = Full_Password1.getText().trim();
    String confirmPass = new String(Full_Password.getPassword()).trim();

 //  Ensure all required fields are filled

    if (email.isEmpty() || newPass.isEmpty() || confirmPass.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Please fill all fields.",
            "Missing Information",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

   // Check if the new password matches the confirmation password

    if (!newPass.equals(confirmPass)) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Passwords do not match.",
            "Password Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

  //  Validate password strength (uppercase, lowercase, number, symbol, 8 chars)

    if (!newPass.matches("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&]).{8,}$")) {
        javax.swing.JOptionPane.showMessageDialog(this, """
                                                        Password must be at least 8 characters and include:
                                                        - Uppercase letter
                                                        - Lowercase letter
                                                        - Number
                                                        - Special character (@, $, !, %, *, ?, & )""",
            "Weak Password",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

   //  Connect to the database
   try (Connection con = DBConnection.getConnection()) {
    if (con == null) {
                JOptionPane.showMessageDialog(this,
                    "Database connection failed.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

        
            String checkQuery = "SELECT user_type FROM Users WHERE email = ?";
            PreparedStatement psCheck = con.prepareStatement(checkQuery);
            psCheck.setString(1, email);
            ResultSet rs = psCheck.executeQuery();

            if (rs.next()) {
                String userTypeInDB = rs.getString("user_type");

                if (!userTypeInDB.equalsIgnoreCase(selectedUserType)) {
                    JOptionPane.showMessageDialog(this,
                        "You cannot reset password for a user of a different type.",
                        "User Type Mismatch",
                        JOptionPane.ERROR_MESSAGE);
                    return;
                }
            } else {
                JOptionPane.showMessageDialog(this,
                    "This email is not registered.",
                    "Email Not Found",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            String currentPassQuery = "SELECT password FROM Users WHERE email = ?";
            PreparedStatement psCurrent = con.prepareStatement(currentPassQuery);
            psCurrent.setString(1, email);
            ResultSet rsCurrent = psCurrent.executeQuery();

if (rsCurrent.next()) {
    String currentPassword = rsCurrent.getString("password");
    if (currentPassword.equals(newPass)) { 
        JOptionPane.showMessageDialog(this,
            "The new password cannot be the same as the old password.",
            "Password Error",
            JOptionPane.ERROR_MESSAGE);
        return;
    }
}

      // Update the user's password 

        String updateQuery = "UPDATE Users SET password = ? WHERE email = ?";
       PreparedStatement psUpdate = con.prepareStatement(updateQuery);
        psUpdate.setString(1, newPass);
        psUpdate.setString(2, email);

        int rows = psUpdate.executeUpdate();

        if (rows > 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Password updated successfully!",
                "Success",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

           // If update is successful, show message and return to login page

            Login login = new Login();
            login.setVisible(true);
            this.dispose();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Password update failed.",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
// Handle any database or unexpected errors

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error: " + e.getMessage(),
            "Database Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
}

    }//GEN-LAST:event_Update_PasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Reset_Password().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Confirm_Password;
    private javax.swing.JLabel Email;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField Full_Email;
    private javax.swing.JPasswordField Full_Password;
    private javax.swing.JTextField Full_Password1;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Pink_Bar;
    private javax.swing.JLabel Reset_Password;
    private javax.swing.JButton Update_Password;
    private javax.swing.JLabel White_Background;
    private javax.swing.JButton logo;
    // End of variables declaration//GEN-END:variables
}
