/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.myproject.Interfaces;

import com.myproject.swproject.DBConnection;
import com.myproject.swproject.Item;
import com.myproject.swproject.NotificationManage;
import com.myproject.swproject.ReporManager;
import com.myproject.swproject.UserSession;
import java.awt.Image;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Najah
 */
public class Search extends javax.swing.JFrame {
    
    private ArrayList<Item> filteredItems = new ArrayList<>();
    private int currentIndex = 0;
    private int userId = UserSession.getUserId();
    /**
     * Creates new form Search
     */
    public Search(){
        initComponents();
        this.setSize(1020, 670);
        this.setLocationRelativeTo(null); 
        loadItemsByType("All");
    }
     
    private void loadItemsByType(String type) {
    try {

        if (type.equalsIgnoreCase("All")) {
            filteredItems = Item.getAllItemsList(userId);
        } else {
            filteredItems = Item.getItemsByItemTypeList(Item.ItemType.valueOf(type.toUpperCase()),userId);
        }

        currentIndex = 0;

        if (!filteredItems.isEmpty()) {
            showItem(currentIndex);
        } else {
            clearItemDisplay();
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error loading items: " + e.getMessage());
    }
}

private void clearItemDisplay() {
    ItemTitle.setText("No items available");
    ItemDescription.setText("");
    ItemCondition.setText("");
    ItemType.setText("");
    ItemLocation.setText("");
    ItemPhoto.setIcon(null);
    ItemPhoto.setText("");
}

private void showItem(int index) {

    if (index >= 0 && index < filteredItems.size()) {

        Item item = filteredItems.get(index);
 
        ItemTitle.setText(item.getTitle());
        ItemDescription.setText(item.getDescription());
        ItemCondition.setText(item.getItemCondition().toString());
        ItemType.setText(item.getItemType().toString());
        ItemLocation.setText(item.getLocation());
        displayImageInLabel(item.getImageUrl());
    }
}

private void displayImageInLabel(String imagePath) {

ImageIcon icon = new ImageIcon("src/main/resources/" + imagePath); 
Image img = icon.getImage(); int labelWidth = ItemPhoto.getWidth();

int labelHeight = ItemPhoto.getHeight(); 
int imgWidth = img.getWidth(null); 
int imgHeight = img.getHeight(null); 

double scaleX = (double) labelWidth / imgWidth; 
double scaleY = (double) labelHeight / imgHeight; 

double scale = Math.min(scaleX, scaleY); int newWidth = (int) (imgWidth * scale); 
int newHeight = (int) (imgHeight * scale); 
Image scaled = img.getScaledInstance(newWidth, newHeight, Image.SCALE_SMOOTH); 
ItemPhoto.setIcon(new ImageIcon(scaled));
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JButton();
        Admin = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        Pink_Bar = new javax.swing.JLabel();
        Home = new javax.swing.JButton();
        Searsh = new javax.swing.JButton();
        Upload_Button = new javax.swing.JButton();
        Message = new javax.swing.JButton();
        Profile_Buttton = new javax.swing.JButton();
        next = new javax.swing.JButton();
        back = new javax.swing.JButton();
        request = new javax.swing.JButton();
        ItemTitle = new javax.swing.JLabel();
        ItemLocation = new javax.swing.JLabel();
        filter1 = new javax.swing.JLabel();
        ItemType = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ItemDescription = new javax.swing.JTextArea();
        ItemPhoto = new javax.swing.JLabel();
        CategoryComboBox = new javax.swing.JComboBox<>();
        ItemCondition = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Menu_Bar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Search");
        getContentPane().setLayout(null);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink_logo.png"))); // NOI18N
        logo.setBorder(null);
        logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoActionPerformed(evt);
            }
        });
        getContentPane().add(logo);
        logo.setBounds(0, 0, 130, 100);

        Admin.setFont(new java.awt.Font("Lucida Fax", 3, 36)); // NOI18N
        Admin.setForeground(new java.awt.Color(255, 102, 102));
        Admin.setText("Search");
        getContentPane().add(Admin);
        Admin.setBounds(420, 30, 140, 43);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Exit.png"))); // NOI18N
        Exit.setBorder(null);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(880, 10, 100, 70);

        Pink_Bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink.png"))); // NOI18N
        getContentPane().add(Pink_Bar);
        Pink_Bar.setBounds(0, 0, 1000, 100);

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Home.png"))); // NOI18N
        Home.setBorder(null);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        getContentPane().add(Home);
        Home.setBounds(20, 520, 100, 100);

        Searsh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Search.png"))); // NOI18N
        Searsh.setBorder(null);
        Searsh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearshActionPerformed(evt);
            }
        });
        getContentPane().add(Searsh);
        Searsh.setBounds(220, 520, 100, 100);

        Upload_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Upload.png"))); // NOI18N
        Upload_Button.setBorder(null);
        Upload_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Upload_ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(Upload_Button);
        Upload_Button.setBounds(410, 520, 100, 100);

        Message.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Message.png"))); // NOI18N
        Message.setBorder(null);
        Message.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MessageActionPerformed(evt);
            }
        });
        getContentPane().add(Message);
        Message.setBounds(630, 530, 110, 80);

        Profile_Buttton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Profile.png"))); // NOI18N
        Profile_Buttton.setBorder(null);
        Profile_Buttton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Profile_ButttonActionPerformed(evt);
            }
        });
        getContentPane().add(Profile_Buttton);
        Profile_Buttton.setBounds(830, 520, 100, 100);

        next.setBackground(new java.awt.Color(229, 170, 58));
        next.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        next.setForeground(new java.awt.Color(102, 51, 0));
        next.setText(">");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next);
        next.setBounds(790, 270, 50, 40);

        back.setBackground(new java.awt.Color(229, 170, 58));
        back.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        back.setForeground(new java.awt.Color(102, 51, 0));
        back.setText("<");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(160, 270, 50, 40);

        request.setBackground(new java.awt.Color(229, 170, 58));
        request.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        request.setForeground(new java.awt.Color(102, 51, 0));
        request.setText("Request Item");
        request.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestActionPerformed(evt);
            }
        });
        getContentPane().add(request);
        request.setBounds(410, 460, 180, 50);

        ItemTitle.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        ItemTitle.setForeground(new java.awt.Color(204, 102, 0));
        ItemTitle.setText("Item Title");
        getContentPane().add(ItemTitle);
        ItemTitle.setBounds(550, 190, 210, 15);

        ItemLocation.setFont(new java.awt.Font("Lucida Fax", 0, 12)); // NOI18N
        ItemLocation.setForeground(new java.awt.Color(91, 45, 0));
        ItemLocation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ItemLocation.setText("Item Location");
        getContentPane().add(ItemLocation);
        ItemLocation.setBounds(550, 390, 210, 15);

        filter1.setFont(new java.awt.Font("Lucida Fax", 3, 18)); // NOI18N
        filter1.setText("Filter by category");
        getContentPane().add(filter1);
        filter1.setBounds(320, 120, 180, 30);

        ItemType.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        ItemType.setForeground(new java.awt.Color(204, 102, 0));
        ItemType.setText("Item Type");
        getContentPane().add(ItemType);
        ItemType.setBounds(550, 330, 210, 15);

        ItemDescription.setEditable(false);
        ItemDescription.setBackground(new java.awt.Color(254, 253, 227));
        ItemDescription.setColumns(20);
        ItemDescription.setFont(new java.awt.Font("Lucida Fax", 0, 14)); // NOI18N
        ItemDescription.setForeground(new java.awt.Color(91, 45, 0));
        ItemDescription.setLineWrap(true);
        ItemDescription.setRows(5);
        ItemDescription.setWrapStyleWord(true);
        jScrollPane2.setViewportView(ItemDescription);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(550, 220, 210, 80);
        getContentPane().add(ItemPhoto);
        ItemPhoto.setBounds(240, 186, 270, 240);

        CategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Clothing", "Bags", "Supplies", "Other" }));
        CategoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoryComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(CategoryComboBox);
        CategoryComboBox.setBounds(500, 120, 140, 30);

        ItemCondition.setFont(new java.awt.Font("Lucida Fax", 1, 12)); // NOI18N
        ItemCondition.setForeground(new java.awt.Color(204, 102, 0));
        ItemCondition.setText("Item Condition");
        getContentPane().add(ItemCondition);
        ItemCondition.setBounds(550, 350, 210, 15);

        jPanel2.setBackground(new java.awt.Color(248, 234, 219));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(230, 170, 540, 280);

        Menu_Bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink.png"))); // NOI18N
        getContentPane().add(Menu_Bar);
        Menu_Bar.setBounds(0, 520, 1000, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/White.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoActionPerformed
        // TODO add your handling code here:
        About_Us about = new About_Us();
        about.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        Welcome_Page newPage = new Welcome_Page();
        newPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        Home newPage = new Home();
        newPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeActionPerformed

    private void SearshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearshActionPerformed

    }//GEN-LAST:event_SearshActionPerformed

    private void Upload_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Upload_ButtonActionPerformed
        // TODO add your handling code here:
        Upload newPage = new Upload();
        newPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Upload_ButtonActionPerformed

    private void MessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MessageActionPerformed
        // TODO add your handling code here:
        Notifications newPage = new Notifications();
        newPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MessageActionPerformed

    private void Profile_ButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Profile_ButttonActionPerformed
        // TODO add your handling code here:
        Profile newPage = new Profile();
        newPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Profile_ButttonActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
                 if (currentIndex < filteredItems.size() - 1) {
                currentIndex++;
                }
                else
                currentIndex = 0;
                 
                showItem(currentIndex);
    }//GEN-LAST:event_nextActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
               if (currentIndex > 0) {
                currentIndex--;
                }
                else
                currentIndex = filteredItems.size() - 1;
                showItem(currentIndex);
            
    }//GEN-LAST:event_backActionPerformed

    private void requestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestActionPerformed
        Item requestdItem = filteredItems.get(currentIndex);
        try(Connection conn = DBConnection.getConnection()){
            
            int donorId = requestdItem.getUserId();
            int itemId = requestdItem.getItemId();
            
            String sql = "UPDATE Items SET status = 'requested' WHERE item_id = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setInt(1, itemId);
            ps.executeUpdate();
            
        ReporManager.createDonationReport(donorId, userId, itemId);
        
        NotificationManage.sendDonationRequestNotification(conn,donorId,itemId);
        } catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
            
    }//GEN-LAST:event_requestActionPerformed

    private void CategoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoryComboBoxActionPerformed
        String selected = (String) CategoryComboBox.getSelectedItem();
        loadItemsByType(selected);
    }//GEN-LAST:event_CategoryComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Search().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin;
    private javax.swing.JComboBox<String> CategoryComboBox;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Home;
    private javax.swing.JLabel ItemCondition;
    private javax.swing.JTextArea ItemDescription;
    private javax.swing.JLabel ItemLocation;
    private javax.swing.JLabel ItemPhoto;
    private javax.swing.JLabel ItemTitle;
    private javax.swing.JLabel ItemType;
    private javax.swing.JLabel Menu_Bar;
    private javax.swing.JButton Message;
    private javax.swing.JLabel Pink_Bar;
    private javax.swing.JButton Profile_Buttton;
    private javax.swing.JButton Searsh;
    private javax.swing.JButton Upload_Button;
    private javax.swing.JButton back;
    private javax.swing.JLabel filter1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logo;
    private javax.swing.JButton next;
    private javax.swing.JButton request;
    // End of variables declaration//GEN-END:variables
}
