/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.myproject.Interfaces;
import com.myproject.swproject.DBConnection;
import com.myproject.swproject.UserSession;
import com.myproject.swproject.ValidationUtils;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
public class Sign_Up extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Sign_Up.class.getName());

    /**
     * Creates new form Sign_Up
     */
    private String selectedUserType;;
    public Sign_Up() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/Logo.png")).getImage());
        this.setSize(1020, 670);
        this.setLocationRelativeTo(null); 
        this.selectedUserType = UserSession.getselectedUserType();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Sign_Up = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Full_Email = new javax.swing.JTextField();
        Username = new javax.swing.JLabel();
        Full_Username = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        Full_Password = new javax.swing.JTextField();
        Confirm_Password = new javax.swing.JLabel();
        LocationComboBox = new javax.swing.JComboBox<>();
        Phone_Number = new javax.swing.JLabel();
        Full_Phone = new javax.swing.JTextField();
        Location = new javax.swing.JLabel();
        Pink_Bar = new javax.swing.JLabel();
        Have_Account = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        Gray_Bar = new javax.swing.JLabel();
        Full_ConfirmPassword = new javax.swing.JPasswordField();
        SignUp = new javax.swing.JButton();
        White_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink_logo.png"))); // NOI18N
        logo.setBorder(null);
        logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoActionPerformed(evt);
            }
        });
        getContentPane().add(logo);
        logo.setBounds(0, 0, 130, 100);

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Smal_Exit.png"))); // NOI18N
        Exit.setBorder(null);
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(870, 10, 100, 70);

        Sign_Up.setFont(new java.awt.Font("Lucida Fax", 3, 36)); // NOI18N
        Sign_Up.setForeground(new java.awt.Color(255, 102, 102));
        Sign_Up.setText("Sign Up");
        getContentPane().add(Sign_Up);
        Sign_Up.setBounds(400, 30, 150, 43);

        Email.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Email.setText("Email:");
        getContentPane().add(Email);
        Email.setBounds(170, 120, 100, 43);

        Full_Email.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        Full_Email.setForeground(new java.awt.Color(153, 153, 153));
        Full_Email.setText("Please enter your Email");
        getContentPane().add(Full_Email);
        Full_Email.setBounds(350, 120, 500, 40);

        Username.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Username.setText("Username:");
        getContentPane().add(Username);
        Username.setBounds(170, 180, 130, 43);

        Full_Username.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        Full_Username.setForeground(new java.awt.Color(153, 153, 153));
        Full_Username.setText("Please enter your Username");
        Full_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Full_UsernameActionPerformed(evt);
            }
        });
        getContentPane().add(Full_Username);
        Full_Username.setBounds(350, 180, 500, 40);

        Password.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Password.setText("Password:");
        getContentPane().add(Password);
        Password.setBounds(170, 240, 130, 43);

        Full_Password.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        Full_Password.setForeground(new java.awt.Color(153, 153, 153));
        Full_Password.setText("Please enter your Password");
        Full_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Full_PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Full_Password);
        Full_Password.setBounds(350, 240, 500, 40);

        Confirm_Password.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Confirm_Password.setText("Confirm Password:");
        getContentPane().add(Confirm_Password);
        Confirm_Password.setBounds(170, 310, 230, 30);

        LocationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Region", "Riyadh Region", "Makkah Region", "Madinah Region", "Qassim Region", "Eastern Province (Ash Sharqiyah)", "Asir Region", "Tabuk Region", "Hail Region", "Northern Borders Region", "Jazan Region", "Najran Region", "Al Bahah Region", "Al Jawf Region" }));
        LocationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(LocationComboBox);
        LocationComboBox.setBounds(410, 420, 440, 30);

        Phone_Number.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Phone_Number.setText("Phone Number:");
        getContentPane().add(Phone_Number);
        Phone_Number.setBounds(170, 360, 190, 30);

        Full_Phone.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        Full_Phone.setForeground(new java.awt.Color(153, 153, 153));
        Full_Phone.setText("Please enter your Phone Number");
        Full_Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Full_PhoneActionPerformed(evt);
            }
        });
        getContentPane().add(Full_Phone);
        Full_Phone.setBounds(410, 360, 440, 40);

        Location.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Location.setText("Location:");
        getContentPane().add(Location);
        Location.setBounds(170, 420, 130, 30);

        Pink_Bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink.png"))); // NOI18N
        getContentPane().add(Pink_Bar);
        Pink_Bar.setBounds(0, 0, 1000, 100);

        Have_Account.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        Have_Account.setForeground(new java.awt.Color(102, 102, 102));
        Have_Account.setText("You already have an account?");
        getContentPane().add(Have_Account);
        Have_Account.setBounds(250, 560, 250, 20);

        login.setBackground(new java.awt.Color(216, 216, 216));
        login.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        login.setForeground(new java.awt.Color(204, 102, 0));
        login.setText("Login");
        login.setPreferredSize(new java.awt.Dimension(1440, 1038));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(540, 550, 190, 40);

        Gray_Bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Gray.png"))); // NOI18N
        getContentPane().add(Gray_Bar);
        Gray_Bar.setBounds(0, 540, 1000, 100);

        Full_ConfirmPassword.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
        Full_ConfirmPassword.setText("Please confirm your Password");
        getContentPane().add(Full_ConfirmPassword);
        Full_ConfirmPassword.setBounds(410, 300, 440, 40);

        SignUp.setBackground(new java.awt.Color(229, 170, 58));
        SignUp.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        SignUp.setForeground(new java.awt.Color(102, 51, 0));
        SignUp.setText("Sign Up");
        SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUpActionPerformed(evt);
            }
        });
        getContentPane().add(SignUp);
        SignUp.setBounds(540, 470, 180, 60);

        White_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/White.png"))); // NOI18N
        White_Background.setToolTipText("");
        getContentPane().add(White_Background);
        White_Background.setBounds(0, 0, 1000, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoActionPerformed
        // TODO add your handling code here:
        About_Us about = new About_Us();
        about.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:

        Welcome_Page newPage = new Welcome_Page();
        newPage.setVisible(true);
       
        this.dispose();
    }//GEN-LAST:event_ExitActionPerformed

    private void Full_PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Full_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Full_PhoneActionPerformed

    private void Full_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Full_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Full_UsernameActionPerformed

    private void Full_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Full_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Full_PasswordActionPerformed
// Opens the Login page and closes the current form

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
       
        Login newPage = new Login();
        newPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginActionPerformed
// Main Sign Up process:
// Validates all input fields, checks data format,
// and inserts a new user into the database if everything is correct
    private void SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUpActionPerformed
        {   
            // Read user input from all text fields
    String email = Full_Email.getText().trim();
    String username = Full_Username.getText().trim();
    String password = Full_Password.getText().trim();
    String confirmPassword = new String(Full_ConfirmPassword.getPassword()).trim();
    String phone = Full_Phone.getText().trim();
    String location = (String) LocationComboBox.getSelectedItem();
// Check if any required field is empty
    if (email.isEmpty() || username.isEmpty() || password.isEmpty() ||
        confirmPassword.isEmpty() || phone.isEmpty() || selectedUserType.isEmpty()) {

        javax.swing.JOptionPane.showMessageDialog(this, 
                "Please fill all fields!",
                "Missing Data",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

 // Check if any required field is empty
    if (!ValidationUtils.isValidEmail(email)) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Invalid email format!",
                "Invalid Email",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

   // Validate password strength based on defined rules
    if (!ValidationUtils.isValidPassword(password)) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Password must be at least 8 characters, contain a number, "
                + "an uppercase letter, and a special symbol (!@#$%^&*).",
                "Weak Password",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

// Check if password and confirm password fields match
    if (!password.equals(confirmPassword)) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Passwords do not match!",
                "Password Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

// Validate that the phone number 
    if (!ValidationUtils.isValidPhone(phone)) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Phone number must be 10 digits.",
                "Invalid Phone Number",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
// Username rules:
if (!username.matches("^[A-Za-z0-9_]{4,}$") || username.matches("^[0-9]+$") || username.matches("^_+$")) {
    javax.swing.JOptionPane.showMessageDialog(this, """
                                                    Username must be at least 4 characters, contain only letters, numbers, or underscores,
                                                    and cannot be all numbers or all underscores.""",
        "Invalid Username",
        javax.swing.JOptionPane.ERROR_MESSAGE);
    return;
}

   // Try connecting to the database and inserting the new user
   try (Connection con = DBConnection.getConnection()) {

    if (con == null) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Database connection failed!",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
      String checkEmail = "SELECT COUNT(*) FROM Users WHERE email = ?";
        PreparedStatement psEmail = con.prepareStatement(checkEmail);
        psEmail.setString(1, email);
        var rsEmail = psEmail.executeQuery();
        rsEmail.next();
        if (rsEmail.getInt(1) > 0) {
            JOptionPane.showMessageDialog(this, "Email already exists!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
  String checkUsername = "SELECT COUNT(*) FROM Users WHERE username = ?";
        PreparedStatement psUsername = con.prepareStatement(checkUsername);
        psUsername.setString(1, username);
        var rsUsername = psUsername.executeQuery();
        rsUsername.next();
        if (rsUsername.getInt(1) > 0) {
            JOptionPane.showMessageDialog(this, "Username already exists!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
       
        String checkPassword = "SELECT COUNT(*) FROM Users WHERE password = ?";
        PreparedStatement psPassword = con.prepareStatement(checkPassword);
        psPassword.setString(1, password);
        var rsPassword = psPassword.executeQuery();
        rsPassword.next();
       if (rsPassword.getInt(1) > 0) {
       JOptionPane.showMessageDialog(this, "Password already exists!", "Error", JOptionPane.ERROR_MESSAGE);
       return;
     }


   
        String checkPhone = "SELECT COUNT(*) FROM Users WHERE phone = ?";
        PreparedStatement psPhone = con.prepareStatement(checkPhone);
        psPhone.setString(1, phone);
        var rsPhone = psPhone.executeQuery();
        rsPhone.next();
        if (rsPhone.getInt(1) > 0) {
            JOptionPane.showMessageDialog(this, "Phone number already exists!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }


    String insert = "INSERT INTO Users (username, email, password, user_type, phone, Location) "
                   + "VALUES (?, ?, ?, ?, ?, ?)";

    PreparedStatement ps = con.prepareStatement(insert);

    ps.setString(1, username);
    ps.setString(2, email);
    ps.setString(3, password);
    ps.setString(4, this.selectedUserType);   
    ps.setString(5, phone);  
    ps.setString(6, location);

    int rows = ps.executeUpdate();

    if (rows > 0) {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Account created successfully!",
                "Success",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

        Login loginpage = new Login();
        loginpage.setVisible(true);
        this.dispose();
    } else {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Failed to create user!",
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
    }

} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this,
            "Error: " + e.getMessage(),
            "Database Error",
            javax.swing.JOptionPane.ERROR_MESSAGE);
   
}          
        }

    }//GEN-LAST:event_SignUpActionPerformed

    private void LocationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Sign_Up().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Confirm_Password;
    private javax.swing.JLabel Email;
    private javax.swing.JButton Exit;
    private javax.swing.JPasswordField Full_ConfirmPassword;
    private javax.swing.JTextField Full_Email;
    private javax.swing.JTextField Full_Password;
    private javax.swing.JTextField Full_Phone;
    private javax.swing.JTextField Full_Username;
    private javax.swing.JLabel Gray_Bar;
    private javax.swing.JLabel Have_Account;
    private javax.swing.JLabel Location;
    private javax.swing.JComboBox<String> LocationComboBox;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Phone_Number;
    private javax.swing.JLabel Pink_Bar;
    private javax.swing.JButton SignUp;
    private javax.swing.JLabel Sign_Up;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel White_Background;
    private javax.swing.JButton login;
    private javax.swing.JButton logo;
    // End of variables declaration//GEN-END:variables
}
