/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.myproject.Interfaces;

import com.myproject.swproject.UserSession;
import javax.swing.ImageIcon;

/**
 *
 * @author shahd
 */
public class Welcome_Page extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Welcome_Page.class.getName());

    /**
     * Creates new form Welcome_Page
     */
    public Welcome_Page() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/Logo.png")).getImage());
        this.setSize(1020, 670);
        this.setLocationRelativeTo(null); 
    }
    
    private void openLogin() {
        Login login = new Login();  
        login.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Welcome = new javax.swing.JLabel();
        Pink_Bar = new javax.swing.JLabel();
        Logo = new javax.swing.JButton();
        Customer = new javax.swing.JButton();
        Admin1 = new javax.swing.JButton();
        White_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to Ataya");
        setName("Welcame Page"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1440, 1038));
        getContentPane().setLayout(null);

        Welcome.setFont(new java.awt.Font("Lucida Fax", 3, 36)); // NOI18N
        Welcome.setForeground(new java.awt.Color(255, 102, 102));
        Welcome.setText("Welcome To");
        getContentPane().add(Welcome);
        Welcome.setBounds(380, 30, 240, 43);

        Pink_Bar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pink.png"))); // NOI18N
        Pink_Bar.setPreferredSize(new java.awt.Dimension(1440, 234));
        getContentPane().add(Pink_Bar);
        Pink_Bar.setBounds(0, 0, 1010, 100);

        Logo.setForeground(new java.awt.Color(255, 255, 255));
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/WhiteLogo.png"))); // NOI18N
        Logo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Logo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoActionPerformed(evt);
            }
        });
        getContentPane().add(Logo);
        Logo.setBounds(280, 110, 430, 390);

        Customer.setBackground(new java.awt.Color(229, 170, 58));
        Customer.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        Customer.setForeground(new java.awt.Color(102, 51, 0));
        Customer.setText("Customer");
        Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerActionPerformed(evt);
            }
        });
        getContentPane().add(Customer);
        Customer.setBounds(580, 520, 180, 60);

        Admin1.setBackground(new java.awt.Color(229, 170, 58));
        Admin1.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        Admin1.setForeground(new java.awt.Color(102, 51, 0));
        Admin1.setText("Admin");
        Admin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin1ActionPerformed(evt);
            }
        });
        getContentPane().add(Admin1);
        Admin1.setBounds(200, 520, 180, 60);

        White_Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        White_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/White.png"))); // NOI18N
        White_Background.setPreferredSize(new java.awt.Dimension(1440, 1038));
        getContentPane().add(White_Background);
        White_Background.setBounds(0, 0, 1010, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Admin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin1ActionPerformed
        UserSession.setselectedUserType("admin");
        openLogin(); 
    }//GEN-LAST:event_Admin1ActionPerformed

    private void CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerActionPerformed
        UserSession.setselectedUserType("customer");
        openLogin(); 
    }//GEN-LAST:event_CustomerActionPerformed

    private void LogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoActionPerformed
        // TODO add your handling code here:
            About_Us about = new About_Us(); 
            about.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_LogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Welcome_Page().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin1;
    private javax.swing.JButton Customer;
    private javax.swing.JButton Logo;
    private javax.swing.JLabel Pink_Bar;
    private javax.swing.JLabel Welcome;
    private javax.swing.JLabel White_Background;
    // End of variables declaration//GEN-END:variables
}
